### ISSUE TITLE
Problem on releases .tar.gz

### ISSUE THREAD

**Issue by nemsia** [YunoHost-Apps/mastodon_ynh#104]
When a file is removed on git the upgrade don't remove the old file, 2 solutions:
- re-use git taged releases
or
- clean the install directory on upgrade

I think the second solution is better.

**Comment by anmol26s** [comment]
I remove the directory for most of my packages. But then you should know what folders and files needs to be backed up before deleting the directory and once the new sources are downloaded from github then these the backed up folders and files needs to be restored into the new sources.

Do you know what needs to be backed up before deleting the directory ?

**Comment by nemsia** [comment]
We need to backup live/public folder and env.production file.

**Comment by yalh76** [comment]
live public folder and .env.production are backuped during upgrade and previous sources files are removed
