### ISSUE TITLE
rbenv: version `2.5.1' is not installed

### ISSUE THREAD

**Issue by MCMic** [YunoHost-Apps/mastodon_ynh#107]
I get this, trying to install the package:

```
Attention : HEAD est maintenant sur 7ac5151b7... Bump version to 2.4.3                                                                                                                  
Attention : Downloading ruby-2.4.1.tar.bz2...                                                                                                                                           
Attention : -> https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.1.tar.bz2                                                                                                              
Attention : Installing ruby-2.4.1...
Attention : Installed ruby-2.4.1 to /opt/mastodon/.rbenv/versions/2.4.1
Attention : 
Attention : rbenv: version `2.5.1' is not installed (set by /opt/mastodon/live/.ruby-version)
Attention : rbenv: version `2.5.1' is not installed (set by /opt/mastodon/live/.ruby-version)
Attention : !!
Attention :   mastodon install's script has encountered an error. Installation was cancelled.
Attention : !!
```

I’m not sure why it installs 2.4.1 but then expects 2.5.1. Should I try the develop branch of the package?

**Comment by nemsia** [comment]
You want to install mastodon or upgrade it ?

**Comment by MCMic** [comment]
Install it.
I had an old installation from a package I modified some time ago but I removed it and as far as I know there are no left overs.

**Comment by frju365** [comment]
Je pense @MCMic que tu as installé Mastodon en activant la liste community et en l'installant simplement depuis l'interface admin ou depuis la commande : yunohost app install mastodon (sans préciser l'url). Ceci est très bien et la liste community est faite pour cela. Malheureusement, après vérification, la liste community se réfère à un commit depuis longtemps périmé : le 3a02566f0a1ad50c3949f715a8bd7660c409d483 datant du 22 Mai 2017, c'est à dire portant sur la version 1.4 de mastodon (avec la version 2.4.1 de ruby).

Je demanderais donc à @nemsia de confirmer la PR : https://github.com/YunoHost/apps/pull/578 (ou de changer pour "HEAD" afin de garder de façon permanente le commit à jour)

**Comment by frju365** [comment]
Well, I spoke in french :// I translate it in english (using Deepl) : 

>I think @MCMic that you installed Mastodon by enabling the community list and simply installing it from the admin interface or from the command: yunohost app install mastodon (without specifying the url). This is very good and the community list is made for that. Unfortunately, after verification, the community list refers to a long outdated commit: the 3a02566 dating from May 22, 2017, i.e. mastodon version 1.4 (with ruby version 2.4.1).
So I would ask @nemsia to confirm PR : YunoHost/apps#578 (or change to "HEAD" to keep the commit permanently updated)

**Comment by nemsia** [comment]
Bonjour,
Merci pour la résolution de ce problème.
Je serais d'avis de mettre HEAD pour suivre la branch master et ne pas faire de PR à chaque mise à jour même si le développement est plutôt calme en se moment.

**Comment by frju365** [comment]
Alors, je ne sais pas si c'est ce problème... mais je ne vois que celui-ci et cette solution ;-) car dans le code actuel de l'app il y a bien `exec_as "$app" $final_path/.rbenv/bin/rbenv global 2.5.1`...

Ok. Par contre, il faudra essayer de rester sur la branche testing pour les révisions majeures et ne merger que si tout est ok.

**Comment by frju365** [comment]
Il ne te reste plus qu'à valider : https://github.com/YunoHost/apps/pull/578

**Comment by nemsia** [comment]
C'est fait,
C'est le fonctionnement j'essaye de suivre, la branch testing pose quelques soucis actuellement avec une installation plus propre de NodeJS.
Pour l'instant je suis dans l'attente de la prochaine version majeur de mastodon car la 2.4.3 n'est pas installable sur Yunohost, la création du 1er utilisateur ne fonctionne plus...

**Comment by frju365** [comment]
I close the issue.

**Comment by MCMic** [comment]
Installation worked.
