### ISSUE TITLE
Problem with email configuration

### ISSUE THREAD

**Issue by frju365** [YunoHost-Apps/mastodon_ynh#108]
Do you know how to configure email ? I failed each time with authentication problem.
My conf is that : 
```
# E-mail configuration
# Note: Mailgun and SparkPost (https://sparkpo.st/smtp) each have good free tiers
# If you want to use an SMTP server without authentication (e.g local Postfix relay)
# then set SMTP_AUTH_METHOD and SMTP_OPENSSL_VERIFY_MODE to 'none' and
# *comment* SMTP_LOGIN and SMTP_PASSWORD (leaving them blank is not enough).
SMTP_SERVER=domaineprincipal.com
SMTP_PORT=587
SMTP_LOGIN=user
SMTP_PASSWORD=pass
SMTP_FROM_ADDRESS=noreply@instance.domaine
SMTP_DOMAIN=domaineprincipal.com # defaults to LOCAL_DOMAIN
SMTP_DELIVERY_METHOD=smtp # delivery method can also be sendmail
SMTP_AUTH_METHOD=plain
#SMTP_CA_FILE=/etc/ssl/certs/ca-certificates.crt
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_ENABLE_STARTTLS_AUTO=true
#SMTP_TLS=true
```

**Comment by nemsia** [comment]
I don't remember how smtp work on yunohost, many test was needed to work with mastodon.
Yunohost need valid `SMTP_FROM_ADDRESS=` to work, no ?

**Comment by frju365** [comment]
yes... and by default, there are no authentication (in the package too). It's not really good :-) And yes, it must be a valid adress.

**Comment by anmol26s** [comment]
@frju365 
Is the email not coming to your inbox? It works for me on the same server, when I do forgotten my password.

**Comment by anmol26s** [comment]
You can configure from here:
https://github.com/YunoHost-Apps/mastodon_ynh/blob/develop/scripts/install#L198-L204

Or upgrade from develop branch. The backup and restore on upgrade script works. If anything went wrong it will be restore to master version.

**Comment by frju365** [comment]
Well, it's a conf without authentification, which doesn't work first with SSL and doesn't work if user owns the email adress... which is quite a good thing to secure it.

**Comment by anmol26s** [comment]
Internal emails are don't have SSL. Do you know any alternate for this. Lot of apps need email configuration and without SSL is not able to communicate well to other servers. 

Maybe warning in readme would be good idea to configure a proper SMTP with SSL configuration should be done if you are will have people using email other then server on which the Mastodon is hosted.

**Comment by nemsia** [comment]
SSL need valid login and password to work, it was used on the beginning of this app and work but was abandoned.

We can add a link with this guide ? : https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Production-guide.md#email-service

**Comment by frju365** [comment]
Finally I achieve to have a good configuration. I updated mastodon documentation just after having it working. However I don't think my PR will be reviewed before christmas (many PR on Mastodon Doc repo are old and not reviewed yet).

cf. : https://github.com/tootsuite/documentation/pull/733


My conf is the same, but if you want it : (content of my .env.production for the ppl who may not know where is mastodon config) : 
# E-mail configuration
# Note: Mailgun and SparkPost (https://sparkpo.st/smtp) each have good free tiers
# If you want to use an SMTP server without authentication (e.g local Postfix relay)
# then set SMTP_AUTH_METHOD and SMTP_OPENSSL_VERIFY_MODE to 'none' and
# *comment* SMTP_LOGIN and SMTP_PASSWORD (leaving them blank is not enough).
SMTP_SERVER=lamartine.eu
SMTP_PORT=587
SMTP_LOGIN='id'
SMTP_PASSWORD='pass'
SMTP_FROM_ADDRESS=BLABLA Mastodon Instance <noreply@mastodon.instance.tld>
SMTP_DOMAIN=domaine.tld # main domain can be found in postfix conf
SMTP_DELIVERY_METHOD=smtp # delivery method can also be sendmail
SMTP_AUTH_METHOD=plain
#SMTP_CA_FILE=/etc/ssl/certs/ca-certificates.crt
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_ENABLE_STARTTLS_AUTO=true
#SMTP_TLS=true

**Comment by yalh76** [comment]
using `SMTP_DELIVERY_METHOD=sendmail` to send mails working fine
