### ISSUE TITLE
Upgrade to 2.5.0 need postgresql-9.5

### ISSUE THREAD

**Issue by nemsia** [YunoHost-Apps/mastodon_ynh#117]
Actually we can't upgrade mastodon instances to 2.5.0 installed on Jessie (Yunohost 2)
https://github.com/tootsuite/mastodon/issues/8590

**Comment by vincentux** [comment]
Et pour ceux qui sont sur Yunohost 3, y a moyen de faire la MAJ en 2.5.0 ?

**Comment by nemsia** [comment]
Fix: https://github.com/YunoHost-Apps/mastodon_ynh/commit/eeec0653ac3e2c38bf6c46c93fdecf28d8dae1ab
