### ISSUE TITLE
Content security policy: blocks the peertube video.

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/mastodon_ynh#118]
Hi @frju365 @nemsia 
The content security policy blocks the peertube videos. 
https://github.com/YunoHost-Apps/mastodon_ynh/blob/develop/conf/nginx.conf#L4-L5
I can understand its dangerous to run scripts which are from third party sites. But can there be solution for this that only peertube can be allowed? Or if not 
videos hosted on same top level domain eg. mastodon.domain.tld and peertube.domain.tld can be allowed?

**Comment by frju365** [comment]
mh... perhaps add : *._DOMAIN_
