### ISSUE TITLE
Mastodon installation constantly&repeatedly failing

### ISSUE THREAD

**Issue by ClitTub** [YunoHost-Apps/mastodon_ynh#122]
title says it all:the installation of mastodon thru yunohost is permanently failing.
![image](https://user-images.githubusercontent.com/45183595/48736997-290aa300-ec4d-11e8-89ab-c192649fc581.png)
![image](https://user-images.githubusercontent.com/45183595/48736935-fc568b80-ec4c-11e8-8be2-38e9736ff14e.png)
willing to tip/get anyone that gets it sorted,drunk until he/she is completely wasted,as time is not wasted,when we're getting wasted.

**Comment by anmol26s** [comment]
I am so sorry for this but this package is not functional yet. There is a another mastodon like clone software available **Pleroma**. Dev says if mastodon is car then Pleroma is bike. You may try this. There devs listen there users and fix things in flash like magic.
https://github.com/YunoHost-Apps/pleroma_ynh

**Comment by anmol26s** [comment]
@ClitTub 
Try the mastodon develop branch.

`$ yunohost app install --debug https://github.com/YunoHost-Apps/mastodon_ynh/tree/develop`

**Comment by ClitTub** [comment]
i tried the mastodon develop branch,as suggested and it is still failing(with the following):

https://paste.yunohost.org/raw/zaqadarule

**Comment by ClitTub** [comment]
i have tried the develop branch,as suggested and it is still failing (with the following):

https://paste.yunohost.org/raw/ikohiwogof

**Comment by ClitTub** [comment]
i have tried the develop branch again,as suggested and it is still failing (with the following):

https://paste.yunohost.org/raw/ikohiwogof

**Comment by anmol26s** [comment]
@ClitTub 

Do: 
`$ curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -`

and try again.

**Comment by ClitTub** [comment]
i did the curling,as suggested and it is still failing with (with the following):

https://paste.yunohost.org/raw/acewoqitul

**Comment by yalh76** [comment]
Hi @ClitTub 

Can you try to install the last version using:

`yunohost app install https://github.com/yalh76/mastodon_ynh --debug`

**Comment by yalh76** [comment]
Feel free to reopen the issue if needed

**Comment by ClitTub** [comment]
why was this closed? where/how can it be reopened?

**Comment by yalh76** [comment]
I closed it because I invited you to try to reinstall 14 days ago using `yunohost app install https://github.com/YunoHost-Apps/mastodon_ynh --debug` 
As you gave no news, I prefered to close it, as you can add comments or reopen it clicking on "Reopen and comment" here

**Comment by ClitTub** [comment]
thanx for still taking care of the issue&thanx for still picking it up 14days ago.i gave no news,because i could not give any news anymore,since my ISP changed in the meantime,which required a HW-change,that does not support ynh anymore (hairpinning issue/missing NAT-loopback).that is why,i gave no news 14days ago,as i am not able to check my ynh anymore,because of the HW-change,caused thru ISP-change.i'd still really like to check&report it back,here though.but unfortunately i am not able to atm,because of the mentioned ISP&HW-change,respectively,that went on in the meantime.there is no "Reopen and comment" on my end here,though.just "Comment",but no "Reopen",that is why i was asking.i'm still curios,if the bug i was running into,still occurs.whish i could check your suggestion,somehow.
