### ISSUE TITLE
MAJ 2.7.0

### ISSUE THREAD

**Issue by vincentux** [YunoHost-Apps/mastodon_ynh#128]
Quelqu'un pour tester la toute dernière mise a jour de Mastodon ? please :pray: 
https://github.com/tootsuite/mastodon/releases/tag/v2.7.0

**Comment by buzzworkers** [comment]
ce package ci est à la dernière version de mastodon ?

**Comment by vincentux** [comment]
Oui sur la branche master la version est toujours en 2.5.2
mais tu peux regarder sur la branche dev qui elle est rendue à la version 2.7.1
https://github.com/YunoHost-Apps/mastodon_ynh/tree/develop  

Pour ma part j'attends (si il ni a pas de bug) que quelqu'un passe cette version sur la branche master ;)

**Comment by vincentux** [comment]
Toujours pas de Mise à jour ? :'(

**Comment by yalh76** [comment]
Package updated to 2.7.4
