### ISSUE TITLE
for or againt change_url implementation in mastodon_ynh

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/mastodon_ynh#133]
Even if `change_url` can break Mastodon Federation, do you agree `change_url` be implemented in Mastodon

[![](https://api.gh-polls.com/poll/01D86JRDS2WF1V5RG8VGEC0V5X/For)](https://api.gh-polls.com/poll/01D86JRDS2WF1V5RG8VGEC0V5X/For/vote)
[![](https://api.gh-polls.com/poll/01D86JRDS2WF1V5RG8VGEC0V5X/Against)](https://api.gh-polls.com/poll/01D86JRDS2WF1V5RG8VGEC0V5X/Against/vote)
[![](https://api.gh-polls.com/poll/01D86JRDS2WF1V5RG8VGEC0V5X/Don't%20care)](https://api.gh-polls.com/poll/01D86JRDS2WF1V5RG8VGEC0V5X/Don't%20care/vote)

**Comment by maniackcrudelis** [comment]
Use the config-panel feature to set a variable that allow or disallow change_url to work.
During the change_url, you throw an error and explain that this setting has to be set to allow changing the url.

Into the config panel, you explain clearly why allowing it could be dangerous.

**Comment by anmol26s** [comment]
Very nice idea by @maniackcrudelis . I think we should go with this.

**Comment by yalh76** [comment]
@anmol26s 
Well, I let you move forward on @maniackcrudelis proposition.

**Comment by anmol26s** [comment]
I would like to implement this other apps too. 

@maniackcrudelis How can we set this warning? Further how this warning can be given for that apps which are only allowed to be installed on root? Mastodon_ynh is good example for this. How can the path part be ignored ?

**Comment by maniackcrudelis** [comment]
I'm not sure I understand your questions @anmol26s.

To set the warning, first a explanation should be given in the readme.
Then, load the setting from the config, with ynh_app_setting_get. If the setting isn't set, you throw an error with an explanation and a link to the config_panel to set the config.

About excluding the path, into the change_url script I guess ?.
Well I guess you can simply check if a different path is given, and simply ignore it and explain that you're doing so.

**Comment by anmol26s** [comment]
> To set the warning, first a explanation should be given in the readme.
> Then, load the setting from the config, with ynh_app_setting_get. If the setting isn't set, you throw an error with an explanation and a link to the config_panel to set the config.

But this will fail the command line check.No?

> Well I guess you can simply check if a different path is given, and simply ignore it and explain that you're doing so.

We can see if there is another path then "/" error exception can be given give warning and asking to choose different path. Should the backup and restore included in the change_url?

**Comment by maniackcrudelis** [comment]
> But this will fail the command line check.No?

Indeed, it will.

> Should the backup and restore included in the change_url?

???

**Comment by anmol26s** [comment]
>     Should the backup and restore included in the change_url?
> ???

The change_url is simple for the app which require nginx path replacement. But if the database is replaced in path, this can be dangerous and can break the app. The backup is done in upgrade so that if app break it can be restored. Similar situation can happen in the change_url too. So, should backup and restore be included in the change_url like upgrade have it?

**Comment by maniackcrudelis** [comment]
Oh ok, we indeed don't use `ynh_backup_before_upgrade` for change_url scripts.
I don't know if it would work, as there's modification as well on domain and path.

Anyway, I think this should be tested. If it works, it could be interesting to add this security to this script.

**Comment by mediaformat** [comment]
...beyond the issue of being for or against, and that it breaks federation. 
I just finished the install, ...had second thoughts and decided on a different url.

The result is my users no longer have a server name, ex: `@user` instead of `@user@domain.tld`

**Comment by yalh76** [comment]
OK then, I will remove the change_url script.
