### ISSUE TITLE
Comment installer de la version develop

### ISSUE THREAD

**Issue by lesamarien** [YunoHost-Apps/mastodon_ynh#135]
Bonjour

Pouvez-vous expliquer comment installer la version develop qui est en 2.7.4. Quand je lance la commande : https://github.com/YunoHost-Apps/mastodon_ynh c'est toujours la version 2.5.2 qui s'installe.

Je suis actuellement sur Yunohost 3.5.2.2

Merci d'avance pour votre aide...

**Comment by vincentux** [comment]
Salut @lesamarien 
as-tu essayé avec ce lien ?
https://github.com/YunoHost-Apps/mastodon_ynh/tree/develop

**Comment by lesamarien** [comment]
Bonjour

Oui je viens de tester et Mastodon s'st bien installé.
Merci
