### ISSUE TITLE
Installation Fail

### ISSUE THREAD

**Issue by raphgilles** [YunoHost-Apps/mastodon_ynh#137]
Hello,

I try to install Mastodon on my Yunohost server since some weeks now, and I don't know why I can't.

Here is the log of my last try :
https://paste.yunohost.org/raw/uyiqahogip

I tried with the develop branch and the master branch. But no one works.

Can you help me ? :)
Thank you !

**Comment by yalh76** [comment]
It seems that you yunohost have some problems to reach httpredir.debian.org using IPV6.

have you tested if IPV6 works on your yunohost ?

You are still in jessie ?

**Comment by raphgilles** [comment]
No I'm on a recent Yunohost 3 installation, so on Stretch.

**Comment by yalh76** [comment]
Can you retry to install Mastodon using: 

`yunohost app install https://github.com/YunoHost-Apps/mastodon_ynh --debug`

And give the link to the logs if installation fail

**Comment by raphgilles** [comment]
And so... The installation failed.

https://paste.yunohost.org/raw/obocobuzos

**Comment by yalh76** [comment]
Perfect. so it seems that jessie backport are configured on your yunohost.
They need to be removed

Can you give the result of 
`ls -la /etc/apt/sources.list.d/yunohost.list`
and of :
`nano /etc/apt/sources.list`

**Comment by raphgilles** [comment]
`-rw-r--r-- 1 root root 53 Apr 17 12:36 /etc/apt/sources.list.d/yunohost.list`

![Sans titdsre-1](https://user-images.githubusercontent.com/49836486/57540177-6292b000-734c-11e9-9268-191180efb401.jpg)

**Comment by yalh76** [comment]
got it.

You need to remove the last line of `nano /etc/apt/sources.list`

With the jessie-backports

**Comment by raphgilles** [comment]
I have an other error, but it's different !

https://paste.yunohost.org/raw/mijuloqoci

**Comment by yalh76** [comment]
weird, because it says that password authentication for the postgresl database failed but all is ok in the logs.

Can you try to reinstall another time using `yunohost app install https://github.com/YunoHost-Apps/mastodon_ynh --debug`

**Comment by raphgilles** [comment]
I tried with the 2.8.2 branche, and it's looks like a succeed !
https://dissidents.social/

But I don't know what is the administrator password ? It's the password of the account that I chose during the install ? Because it doesn't work.

And when I try to create a new user, I don't receive emails.

**Comment by yalh76** [comment]
lol 2.8.2 wasn't ready but cool :)

The administrator password has been sent by mail to the user you choose during the installation.
It's a different password from the password of the account you choose during install.

**Comment by raphgilles** [comment]
Lol I try every branches since some weeks now !

That's a problem :
First because the email doesn't exist, Yunohost force me to use the domains installed on. But I don't have any existing email from theim.
And also because I think I have a configuration problem for the emails. When I create an account, I don't receive the confirmation email.

**Comment by yalh76** [comment]
the user you pick in the list has an email address, at least it's root@dissidents.social
So you only need to install something like rainloop to access the email.

For confirmation mail not received, I have to make some tests

**Comment by raphgilles** [comment]
Ok. I have find my password with rainloop. Thank you.

Last problem (I hope) : the emails configuration. I tried with 2 differents services (gmail & protonmail) and I don't receive the validation mail.

**Comment by yalh76** [comment]
Good, 

For the mails, I'm looking to solve the problem. Mails are currently stucked in mastodon. I will try other mail configuration and update to solve it

**Comment by yalh76** [comment]
Mail issue solved, now in the master branch
