### ISSUE TITLE
Webapp conflicts with Adguard

### ISSUE THREAD

**Issue by csolisr** [YunoHost-Apps/mastodon_ynh#155]
## Steps
1. Install Adguard on a subdomain (like dns.example.net)
2. Install Mastodon on a different subdomain (like mastodon.example.net)

## Expected result
Both Adguard and Mastodon can be accessed through their respective subdomains.

## Actual result
Trying to access Mastodon through its own subdomain redirects erroneously to Adguard's landing page.

**Comment by yalh76** [comment]
Maybe this issue is made by adguard. 
Do you tried to uninstall it to see if mastodon is working ?

**Comment by csolisr** [comment]
I did uninstall Adguard temporarily, and Mastodon does display a landing page, but on the other hand the app is not working properly so it displays an error message instead.

**Comment by yalh76** [comment]
Can you try to uninstall and reinstall Mastodon first and if it's working, try to install adguard.

**Comment by yalh76** [comment]
Let us know when you made some tests and we reopen that issue if needed.
