### ISSUE TITLE
Upgrade stuck at "initialize authenticator"

### ISSUE THREAD

**Issue by rosareven** [YunoHost-Apps/mastodon_ynh#156]
![image](https://user-images.githubusercontent.com/17244066/59445318-57251f80-8df7-11e9-9f6b-48de91b301f5.png)
It seems to just get stalled at this step. On the web gui it is stuck at loading as well.

**Comment by yalh76** [comment]
Can you try instead : 
`yunohost app upgrade mastodon -u https://github.com/YunoHost-Apps/mastodon_ynh --debug`

Seems more an issue on your yunohost than an issue with mastodon.

Have you tried to upgrade other apps ?

**Comment by rosareven** [comment]
The update is successful now, although stuck at the backup step. 

I've also updated the generic web app and Wallabag from my yunohost web interface without issue.

**Comment by yalh76** [comment]
Ok then, I updated the command to upgrade in the readme
