### ISSUE TITLE
Mastodon 2.9.0 - plus d'image...

### ISSUE THREAD

**Issue by vincentux** [YunoHost-Apps/mastodon_ynh#159]
Suite à la mise à jour en v2.9.0, les images ne s'affichent plus :(  
Une idée comment régler ce souci ?

![2019-06-16_15-02-04](https://user-images.githubusercontent.com/11737560/59564494-de68d200-9047-11e9-89da-a6ff4fd7d70c.png)

**Comment by yalh76** [comment]
OK, I have to test that.. I let you know

**Comment by vincentux** [comment]
Juste pour info, les images s'affichent bien avec Fedilab (android)

**Comment by yalh76** [comment]
J'ai fait quelques tests et de mon coté cela semble fonctionner. De plus dans ton screenshot, il y a bien une image qui s'affiche dans le poste de shinra....

**Comment by vincentux** [comment]
Oui c'est vraiment curieux, certaines images passent et pas d'autres... idem pour les avatars :/

**Comment by mediaformat** [comment]
me semble avoir lu que c'est un filtre ou une préférence qui affiche les images flouées

**Comment by vincentux** [comment]
Non mais je peux voir les images flouées quand elle sont là,
mais c'est aussi les avatars qui ne s'affichent pas.

**Comment by yalh76** [comment]
1. Est ce que tu as essayé le cache de ton navigateur ?
2. Essayé avec un autre navigateur ?
3. Essayé depuis un autre ordinateur ?

**Comment by MCMic** [comment]
J’ai le même problème depuis la mise à jour vers 2.8 déjà.
Pour les avatars je crois que je ne vois que ceux qui ont été changés depuis ma mise à jour.

Pour les images dans les pouets ça semble marcher depuis.

**Comment by fflorent** [comment]
J'ai le même souci.

> Est ce que tu as essayé le cache de ton navigateur ?

Oui

> Essayé avec un autre navigateur ?

Oui (Firefox Developer Edition)

> Essayé depuis un autre ordinateur ?

Non mais je doute que ça en soit la cause.

On voit pas mon propre avatar : https://mastodon.zeteo.me/@florent

Des idées ?

**Comment by fflorent** [comment]
Switching to English (sorry for people not speaking French).

FWIW, I suspect the command `RAILS_ENV=production bin/tootctl cache clear` (advised to be run on 2.9.0 upgrade) to be the cause of this dysfunction. I hope it will help to investigate.

**Comment by yalh76** [comment]
English or french not problem but better in English for all mastodon_ynh users ^^

As far I've seen it's ok to do `RAILS_ENV=production bin/tootctl cache clear`, the command is sometimes required for some updates...

But thanks to give me the link to your mastodon instance, I was able to see the problem.

When I try to see your avatar image, I've:
![mastodon](https://user-images.githubusercontent.com/30271971/60132799-88f59900-979c-11e9-99aa-2f934849d0bd.PNG)

Very helpfull, I've found:
- https://github.com/tootsuite/mastodon/issues/7640

For some people, it's because ffmpeg or imagemagick are broken.

Can you check if your avatar photo is in: `/var/www/mastodon/live/public/system/accounts/avatars/000/000/001/original/` it might be the 5aa09ccb69c36883.png file

**Comment by yalh76** [comment]
I found the issue. during upgrade the folder containing image wasn't keept. This issue was present since 2.6.1, https://github.com/YunoHost-Apps/mastodon_ynh/commit/9d07d121ad516bf0d3db1c5eb700cb6575630802#diff-44cb16c778719320333118c04d509a7cR112

**Comment by fflorent** [comment]
Thanks for your answer!

> Can you check if your avatar photo is in: /var/www/mastodon/live/public/system/accounts/avatars/000/000/001/original/ it might be the 5aa09ccb69c36883.png file

It is not:

```bash
$ ls /var/www/mastodon/live/public/system/accounts/avatars/000/000/
191/ 205/ 275/ 302/ 351/ 457/ 565/ 593/ 599/ 707/ 776/ 937/
```

**Comment by yalh76** [comment]
> 
> 
> Thanks for your answer!
> 
> > Can you check if your avatar photo is in: /var/www/mastodon/live/public/system/accounts/avatars/000/000/001/original/ it might be the 5aa09ccb69c36883.png file
> 
> It is not:
> 
> ```shell
> $ ls /var/www/mastodon/live/public/system/accounts/avatars/000/000/
> 191/ 205/ 275/ 302/ 351/ 457/ 565/ 593/ 599/ 707/ 776/ 937/
> ```

So https://github.com/YunoHost-Apps/mastodon_ynh/pull/163 will solve the problem
You have to wait it's merged to the master branch and then you need to remove and restore mastodon_ynh before the upgrade and apply the new upgrade.

I will let you know when fix will be available in the master branch

**Comment by yalh76** [comment]
Fix is now in master branch

**Comment by fflorent** [comment]
Well, I have made a mistake and applied the upgrade without your instructions (that's my fault).

That's hopefully an instance I am the only one to use, so there is no much damages. I guess the images are lost.

Is there any way to just tell mastodon to fetch again remote images (avatars, etc.)? Thanks!

**Comment by yalh76** [comment]
For the images, you can find them in the backup made before the upgrade.

And it seems that the remote images are automatically fetched if needed.

**Comment by fflorent** [comment]
Yeah, but I don't have the backup anymore (I guess that's because the upgrade removes the previous backup…)

**Comment by MCMic** [comment]
Same problem here, any idea how I can get images back?

I tried to use «sudo -u mastodon bin/tootctl account refresh --all» from /var/www/mastodon/live and it did not work:
```
Could not find rake-12.3.2 in any of the sources
Run `bundle install` to install missing gems.
```

What is the correct way to call tootctl?

**Comment by yalh76** [comment]
> 
> 
> Same problem here, any idea how I can get images back?
> 
> I tried to use «sudo -u mastodon bin/tootctl account refresh --all» from /var/www/mastodon/live and it did not work:
> 
> ```
> Could not find rake-12.3.2 in any of the sources
> Run `bundle install` to install missing gems.
> ```
> 
> What is the correct way to call tootctl?

You want to retrieve photos from you instance or photo from other instances ?

To run tootctl, you need to add the environnement like :
`sudo -u mastodon env PATH=$PATH:/opt/rbenv/versions/2.6.1/bin/ RAILS_ENV=production bin/tootctl ....`

**Comment by MCMic** [comment]
> You want to retrieve photos from you instance or photo from other instances ?

Mostly other instances, from my instance there is only my avatar and header, I can reupload them if needed.

> To run tootctl, you need to add the environnement like :
> `sudo -u mastodon env PATH=$PATH:/opt/rbenv/versions/2.6.1/bin/ RAILS_ENV=production bin/tootctl ....`

This gives me the same answer about rake-12.3.2 missing.

**Comment by fflorent** [comment]
> This gives me the same answer about rake-12.3.2 missing.

Same for me :/.

**Comment by yalh76** [comment]
you also have the error doing :
`(cd /var/www/mastodon/live && sudo -u mastodon env PATH=$PATH:/opt/rbenv/versions/2.6.1/bin/ RAILS_ENV=production bin/tootctl account refresh --all)`

**Comment by fflorent** [comment]
Yep :/

```
root@zeteo:/var/www/mastodon/live# sudo -u mastodon env PATH=$PATH:/opt/rbenv/versions/2.6.1/bin/ RAILS_ENV=production bin/tootctl account refresh --all
Could not find rake-12.3.2 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by yalh76** [comment]
Well, then, you can try ti install missing gems using: `(cd /var/www/mastodon/live && sudo -u mastodon env PATH=$PATH /opt/rbenv/versions/2.6.1/bin/bundle install)`

**Comment by MCMic** [comment]
@yalh76 This command is happy with what is already there:

```
# sudo -u mastodon env PATH=$PATH /opt/rbenv/versions/2.6.1/bin/bundle install
Using rake 12.3.2    
[Lots and lots of lines starting with Using]
Using webpush 0.3.8
Bundle complete! 117 Gemfile dependencies, 197 gems now installed.
Gems in the groups development and test were not installed.
Bundled gems are installed into `./vendor/bundle`
```

But it still complains about rake 12.3.2:
```
# sudo -u mastodon env PATH=$PATH:/opt/rbenv/versions/2.6.1/bin/ RAILS_ENV=production bin/tootctl account refresh --all
Could not find rake-12.3.2 in any of the sources                                                                                                                                        
Run `bundle install` to install missing gems. 
```

**Comment by yalh76** [comment]
Can you do `getent passwd mastodon` and provide the result ?

**Comment by fflorent** [comment]
I could make it work using these steps:

```bash
# su - mastodon
$ cd /var/www/mastodon/live
$ bundle install
$ PATH=$PATH:/opt/rbenv/versions/2.6.1/bin/ RAILS_ENV=production bin/tootctl account refresh --all
```

I got this output: `Scheduled refreshment of 13880 accounts`

Waiting for the refreshment to operate :).

**Comment by yalh76** [comment]
Well... we will see...

**Comment by fflorent** [comment]
Some images already back! :heart_eyes:

**Comment by MCMic** [comment]
Ok, so I did not want to install bundler on my system, so I digged a bit into rbenv and found a solution that works, you need to put /opt/rbenv/shims at the begining of the PATH:
```
sudo -u mastodon env PATH=/opt/rbenv/shims:$PATH bundle install
sudo -u mastodon env PATH=/opt/rbenv/shims:$PATH RAILS_ENV=production bin/tootctl account refresh --all
```

Refresh is in process, seems to work.
