### ISSUE TITLE
401The access token is invalid | Maston on YUNOHOST

### ISSUE THREAD

**Issue by JRelland** [YunoHost-Apps/mastodon_ynh#166]
Hi, thank you for Mastodon on YNH.

Installation, user settings and User interface are ok
But cannot use it, always this message.

Note I've seen the 2017 post on an old version.

Thank you for your feedback.
Best regards, José

**Comment by yalh76** [comment]
https://github.com/YunoHost-Apps/mastodon_ynh/issues/167#issuecomment-511216696
