### ISSUE TITLE
You don't have permission to view this page for https://mastodon.bacasable.eu/admin/dashboard

### ISSUE THREAD

**Issue by JRelland** [YunoHost-Apps/mastodon_ynh#167]
Hi, 
thank you for making Mastodon pod creation possible and easy with YUNOHOST

I tried to connect the admin interface through
https://mastodon.bacasable.eu/admin/dashboard

but I got this message:
> You don't have permission to view this page. 

First, thank you for this excellent animation, an elephant hitting the keyboard.
This avoids me to react like that and it was a relaxing instant. 

And thank you for your feedback.
I presume that during the installation process, the repertory is not public.

Please, note I am the same issue with another (YNH-installed) application where the user side is OK but I cannot reach a repertory needed for settings (OWA on WP)
And I have a "401 access token is invalid" error (see my post)
 
Again, thank you for your feedback on this specific issue.

Best Regards, José from France.

**Comment by yalh76** [comment]
I think that you can't access the dashboard because you are not connected with an admin account.
Have you tried to log first with the login and password received by mail in the root mailbox ?

**Comment by JRelland** [comment]
Hi @yalh76 thank you for this quick feedback.

OK, something is confusing for me.

I did not take account of this email, I created straightly a new account called @mastodon@bacasable.eu when I opened Mastodon from my YNH interface. I was thinking it was the superuser account.

Now, I see the email for "@jrelland@mastodon.bacasable.eu". jrelland is the YNH superuser account.
I clicked on the link I was expecting to create the superuser account but, in fact, I return to the @mastodon@bacasable.eu.

See below
![Compte Mastodon Tricassinux ](https://user-images.githubusercontent.com/10448655/61185847-ff7c0d00-a65d-11e9-8cce-08f52c83ed1a.JPG)


Could you note the url: https://mastodon.bacasable.eu/web/accounts/2

The number 2 drawn my attention, I replace it by 1!
And ho! the superadmin account :+1: 
![Screenshot_2019-07-14 jrelland account](https://user-images.githubusercontent.com/10448655/61185815-ccd21480-a65d-11e9-8c02-ccdcb799d804.png)


But I wonder if it is the source of the issue has in fact I did not reach the login page.

Thank you for your time a Sunday.

Best Regards, José.

**Comment by JRelland** [comment]
Hum,
The administrator guide is not really friendly for non-coder

I think I am about to delete this instance in YNH and to recreate one and this time, start with the email :).
I will see if I have both issues :)

Best regards :).

**Comment by JRelland** [comment]
Hi thank for this feedback
I am reinstalling Mastodon.

Je crois que tu parles français.

Je prépare une conférence utilisateur sur les réseaux sociaux
décentralisés. Avec diapora* et Mastodon comme exemple concret.
J'aimerai t'envoyer une copie pour commentaires :)

Amicalement José

**Comment by yalh76** [comment]
> 
> 
> Hum,
> The administrator guide is not really friendly for non-coder
> 
> I think I am about to delete this instance in YNH and to recreate one and this time, start with the email :).
> I will see if I have both issues :)
> 
> Best regards :).

I updated the README to make it more user friendly.

**Comment by yalh76** [comment]
> diapora* et Mastodon comme exemple concret. J'aimerai t'envoyer une copie pour commentaires :)

Oui tu peux m'envoyer ça, Juste pas sûr d'avoir le temps de la relire et je suis vraiment pas un spécialiste des réseaux sociaux ^^

**Comment by JRelland** [comment]
Aîe

Juste terminer le tuto de l'admin

et j'entre dans mon compte admin avec une fenêtre complète de
<https://mastodon.bacasable.eu/web/lists>
------------------------------

401The access token is invalid
401The access token is invalid
401The access token is invalid
401The access token is invalid
401The access token is invalid
-

Bon, je continue, je suis en mode découverte, bacasable sert à àa :)
-
Cordialement

M. José RELLAND
jose.relland@gmail.com
+33 (0)6 79 48 49 97
Vidéo-conférence : https://meet.jit.si/

[+] Please keep my contact details up-to-date
<https://ws.evercontact.com/kwaga-bin/titan/WEB/me.pl/2931835391445501472/i>

**Comment by yalh76** [comment]
Il faut sans doute vider le cache de ton navigateur

**Comment by JRelland** [comment]
Bonjour,

Vider le cache de mon FF n'a rien changé.

De mon compte Mastodon de chez FramaPiaf, je peux voir @
jrelland@mastodon.bacasable.eu

Je peux lui envoyer des MP et le mentionner dans un post.
Mais il ne reçoit rien.


Merci d'avance d'un retour.
-- 
Cordialement

M. José RELLAND
jose.relland@gmail.com
+33 (0)6 79 48 49 97
Vidéo-conférence : https://meet.jit.si/

[+] Please keep my contact details up-to-date
<https://ws.evercontact.com/kwaga-bin/titan/WEB/me.pl/2931835391445501472/i>

**Comment by yalh76** [comment]
Est ce que tu peux vérifier si le service mastodon-sidekiq est fonctionnel ?
`service mastodon-sidekiq status`

**Comment by JRelland** [comment]
Bonjour,
Merci du retour et de la ligne de commande :
Résultat :

jre@bacasable:/$ sudo service mastodon-sidekiq status
● mastodon-sidekiq.service - mastodon-sidekiq
   Loaded: loaded (/etc/systemd/system/mastodon-sidekiq.service; enabled; vendor
 preset: enabled)
   Active: active (running) since Sun 2019-07-14 18:14:54 CEST; 1 day
 2h ago
 Main PID: 13793 (bundle)
    Tasks: 32 (limit: 4915)
   CGroup: /system.slice/mastodon-sidekiq.service
           └─13793 sidekiq 5.2.7 live [0 of 25 busy]

Jul 15 20:55:03 bacasable.eu bundle[13793]: 2019-07-15T18:55:03.910Z 13793 TID-g
slkas02l Scheduler::ScheduledStatusesScheduler JID-9616c8550f37b9a19ac7c5f6 INFO
: done: 0.018 sec
Jul 15 21:00:03 bacasable.eu bundle[13793]: 2019-07-15T19:00:03.705Z 13793 TID-g
slkfmq41 INFO: queueing Scheduler::ScheduledStatusesScheduler (scheduled_statuse
s_scheduler)
Jul 15 21:00:03 bacasable.eu bundle[13793]: 2019-07-15T19:00:03.720Z 13793 TID-g
slkzgmot Scheduler::ScheduledStatusesScheduler JID-5e9f216fabd942d813180f0f INFO
: start
Jul 15 21:00:03 bacasable.eu bundle[13793]: 2019-07-15T19:00:03.742Z 13793 TID-g
slkzgmot Scheduler::ScheduledStatusesScheduler JID-5e9f216fabd942d813180f0f INFO
: done: 0.021 sec
Jul 15 21:05:03 bacasable.eu bundle[13793]: 2019-07-15T19:05:03.906Z 13793 TID-g

Je reste disponible pour toi.

Amicalement, José

**Comment by yalh76** [comment]
Je suis vraiment pas un spécialiste de Mastodon, donc difficile de savoir ce qui peut te bloquer. Il faudrait peut être plus voir sur le repository de Mastodon https://github.com/tootsuite/mastodon

**Comment by JRelland** [comment]
Merci de ton aide.

je viens de poster une issue : #11325

Je partagerai la solution... si je l'ai :)

Bonne fin de soirée :)

Amicalement, José
