### ISSUE TITLE
Install problems / troubleshooting wss://

### ISSUE THREAD

**Issue by aslmx** [YunoHost-Apps/mastodon_ynh#169]
Hi,

just tried again to install the mastodon package. Took some time and ran through with some warnings. 
Eventually install succeeded and i can login. 

However i have two...update: one... problems - and i hope it is okay to post them here...

1. I still suffer from the HTTP 401 issue in firefox. I have uncommented the access/lua thing in the nginx config for the mastodon domain. 
I have logged out, i have cleared cache and restarted firefox... no success. It works in firefox Private mode. It also works in Chromium without private mode. 
I guess this is a firefox thing, but as two other mastodon instances work fine in firefox, i think it might be the combination.

Update: It seems that this one was solved by again restarting (not only reloading) nginx... not sure why there is a difference, but i'm no expert...

2. My federated timeline is empty (altough i'm following 3 users on 2 other instances. When checking the browser console, i get

in firefox:

Content Security Policy: The page’s settings observed the loading of a resource at wss://social.domain.tld/api/v1/streaming/?stream=user (“default-src”). A CSP report is being sent.
Content Security Policy: The page’s settings observed the loading of a resource at wss://social.domain.tld/api/v1/streaming/?stream=public:local (“default-src”). A CSP report is being sent.
Firefox can’t establish a connection to the server at wss://social.domain.tld/api/v1/streaming/?stream=public:local. index.js:59
The connection to wss://social.domain.tld/api/v1/streaming/?stream=public:local was interrupted while the page was loading. index.js:59
Content Security Policy: The page’s settings observed the loading of a resource at wss://social.domain.tld/api/v1/streaming/?stream=public (“default-src”). A CSP report is being sent.

in chromium:
Report Only] Refused to connect to 'wss://social.domain.tld/api/v1/streaming/?stream=public' because it violates the following Content Security Policy directive: "default-src https: data: 'unsafe-inline' 'unsafe-eval'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.

So... i guess i need some additional steps? But i can't find anything useful.

Thanks for your help!

**Comment by aslmx** [comment]
Maybe this is irrelevant.. 

i just found out that there seems to be a max age of posts that can be fetched. I followed some more people and i saw a different number of toos they made. 

Then I also found that there are federation relays (which i never heard of so far), i foudn a working one and suddenly the federated timeline was populated. 

From what i read i had expected the federated timeline to be populated by following people from different instances alone, which seems not to be true.

Anyway, as i think the most valueable thing on mastodon is the local timeline, which is of course pretty empty on small instances, i decided to not extend my self hosting mastodon experiment for now. 

Thanks for reading anway and providing the install script as it made it possible to at least have a look without spending days of getting all that stuff running :)

**Comment by fancycade** [comment]
Hi, I'm having very similar issues with wss.

Is there a fix for this? Or did I accidentally screw up something on the domain side?

**Comment by yalh76** [comment]
Your issue seems related to https://github.com/YunoHost-Apps/mastodon_ynh/issues/6

**Comment by yalh76** [comment]
Feel free to reopen that issue if it's different from #6
