### ISSUE TITLE
Fail MAJ vers 2.9.3

### ISSUE THREAD

**Issue by vincentux** [YunoHost-Apps/mastodon_ynh#174]
Désolé du pavé, mais voici les logs de l'échec de la MAJ ... :/ 

https://framabin.org/p/?23162a47613a6e05#SFL8EcRU1wZha10AW6rCf/mUraAnRUz2oghqS5Iwe1k=  

Une idée ?

**Comment by vincentux** [comment]
Maintenant je souhaite le réinstaller via l'UI et j'ai ce message ...

https://framabin.org/p/?d41eb59f3d4693de#FbOhQGSVdL6A7fdHTvqvyOvXGLX69O3Cp8P+CnYD5lc=

**Comment by yalh76** [comment]
Can you provide the full logs instead of partial logs?

**Comment by vincentux** [comment]
Désolé, je pensais que c'était déjà assez mais si tu en veux plus, voici la came... :package: 

https://framabin.org/p/?dfa0215e23b9cffe#F1jQIBmjdiJ2WKQKmlHNbyn10Jwes5qIVOlRLymDLgc=

**Comment by yalh76** [comment]
Ton erreur ligne 732

2019-08-15 19:27:39,738: WARNING - IOError: [Errno 28] No space left on device
