### ISSUE TITLE
Performance of the upgrade script moving medias

### ISSUE THREAD

**Issue by HugoPoi** [YunoHost-Apps/mastodon_ynh#175]
Is the `rsync -a` necessary in place of a `mv` because it's currently very slow to do a full copy of all medias and delete the source 3 lines after ?

https://github.com/YunoHost-Apps/mastodon_ynh/blob/b9086682d2d7762d2882fff2cda4f5dceb73e32b/scripts/upgrade#L172-L178

For example I upgrade my instance, I'm alone on it. It took `action [2585.1] executed in 2490.312s`

**Comment by yalh76** [comment]
idk, it was like that when I started to work on that package. Maybe not the best way to manage the upgrade...

**Comment by yalh76** [comment]
Well I reread the core.

1. We first move the whole previous mastodon files
2. we download last version
3. from the previous mastodon version we retrieve all the public/system files
4. we also retrieve the .env.production
5. at the end we remove previous version 

If you think that there is better way to manage that, feel free to do a PR ;)

**Comment by HugoPoi** [comment]
Due to this behavior, the upgrade is broken.
Now the script using the /tmp directory. So the script assume you have enough space to copy the entire medias attachments to /tmp.
Me > working on it.

**Comment by yalh76** [comment]
lol too much media...

**Comment by HugoPoi** [comment]
I will launch a `sudo -u mastodon RAILS_ENV=production bin/tootctl media remove` but I'm pretty sure I have done this sometimes ago
