### ISSUE TITLE
Migrating old instance to Yunohost

### ISSUE THREAD

**Issue by vibhi19** [YunoHost-Apps/mastodon_ynh#177]
So i wanted to run my mastodon instance using yunohost but i wanted to transfer my old instance so what is the process to move?

I know about migrating doc but Yuno take care of everything so how mastodon migration will be done on Yuno and doc also say not to run mastodon:setup when you migrating server 

FYI my media is already on Wasabi S3

**Comment by yalh76** [comment]
Is your old instance on a YunoHost ?

**Comment by vibhi19** [comment]
> Is your old instance on a YunoHost ?

No, its on CentOS with CPanel

**Comment by yalh76** [comment]
Ok then, there is no migration tool provided by YunoHost. You will need to follow the steps: https://docs.joinmastodon.org/fr/administration/migrating/
