### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by JeanCharpentier** [YunoHost-Apps/mastodon_ynh#185]
Hi !
I get error while I try to install mastodon to Yunohost.
Here is the log : https://paste.yunohost.org/raw/cusezuwugu

I'd already install Pixelfed and Peertube, if it can help...
Thank you

**Comment by yalh76** [comment]
Seems an error when adding some swap, I have to check that

**Comment by JeanCharpentier** [comment]
Ok thank you ! Do you need more infos about the VPS I'm using ?
If so, what command can I use to give you this infos ?

**Comment by yalh76** [comment]
Do you was root when installing mastodon ?
Maybe you shoud try to install from the command line as root.

**Comment by JeanCharpentier** [comment]
Thank you. I'd try with sudo and as root (sudo su) and had the same message.

**Comment by yalh76** [comment]
Maybe it comes from your vps, do you have more details about it ?

**Comment by yalh76** [comment]
Without news, I close that issue. Feel free to reopen that issue
