### ISSUE TITLE
Upgrade fail (3.0.1~ynh1 to 3.0.1~ynh2)

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/mastodon_ynh#188]
I tried several times to upgrade mastodon but the service now fails to start.

The logs are here: https://paste.yunohost.org/raw/umisamikah

It's a bit confusing and I am not sure how I can help diagnose this. I am following the master branch and lately I tried to upgrade to the last commits, with no success.

**Comment by yalh76** [comment]
It's like the service mastodon_ynh wasn't able to stop... Maybe it wasn't started when you try to upgrade ? 
You have to be sure mastodon-web; mastodon-streaming and mastodon-sidekiq are running before upgrading.

**Comment by fflorent** [comment]
Well, unfortunately I cannot start the service. The logs after `sudo yunohost service start mastodon-sidekiq --debug` are here:
https://paste.yunohost.org/elapehexif.vbs

Thanks in advance!

**Comment by fflorent** [comment]
Any news? I have a backup named `mastodon-pre-upgrade2.tar.gz` that may help. Thanks!

Florent

**Comment by yalh76** [comment]
maybe you should restore that backup doing:
- `yunohost app remove mastodon`
- `yunohost backup restore mastodon-pre-upgrade2 --apps mastodon --debug`

When restored and sure that all mastodon services are ok, you can retry to upgrade

**Comment by fflorent** [comment]
My bad, I omitted to say I managed to run the backup restoration. It went all fine.

Thanks and happy new year! :)

Florent

**Comment by yalh76** [comment]
> 
> 
> My bad, I omitted to say I managed to run the backup restoration. It went all fine.
> 
> Thanks and happy new year! :)
> 
> Florent

Cool, sorry for the delay, I'm quite busy at that time.

Happy new year too :)

**Comment by fflorent** [comment]
All fine, I understand :)
