### ISSUE TITLE
reset admin Password

### ISSUE THREAD

**Issue by Vibhigupta** [YunoHost-Apps/mastodon_ynh#197]
in yunohost i have disabled the mail box fucntion in user so where i am going to receive that password.

it would be better if you can guide me a way to reset it.

**Comment by Vibhigupta** [comment]
and How it sends mail to user? via its own php mail or sendmail?

**Comment by yalh76** [comment]
The password is sent using /usr/bin/mail.mailutils to the email attached to the account you choose during the installation. 

To reset the password you can do `(cd /var/www/mastodon/live && sudo -u mastodon env PATH=/opt/rbenv/shims:/opt/rbenv/bin:/opt/node_n/n/versions/node/10/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RAILS_ENV=production bin/tootctl accounts modify USERNAME --reset-password)` replacing USERNAME by the username you choose during installation.

Mastodon use internal postfix server : 
https://github.com/YunoHost-Apps/mastodon_ynh/blob/6f5fc5445e7e3570769192e316394bf440405e3a/conf/.env.production.sample#L62-L79
