### ISSUE TITLE
Mastodon won't install

### ISSUE THREAD

**Issue by frandavid100** [YunoHost-Apps/mastodon_ynh#202]
When I try to install Mastodon on Yunohost, I get an error. This is the log:

https://paste.yunohost.org/raw/uvexagomiv

From what I've gathered, it's related to this bug:

https://github.com/tootsuite/mastodon/issues/13292

**Comment by harding** [comment]
I believe I've encountered the same problem; it won't install and the last dozen or so lines in my log are the same as pasted above.

**Comment by yalh76** [comment]
Yes it seems to be a recent issue. will have to wait the next release
