### ISSUE TITLE
upgrade feedback

### ISSUE THREAD

**Issue by MCMic** [YunoHost-Apps/mastodon_ynh#203]
I’m upgrading mastodon, it’s stuck after :
```
 [++..................] > Backing up the app before upgrading (may take a while)...
Attention : 158624 Please wait, the service mastodon-web is starting....................................................................................
Attention : 177043 Please wait, the service mastodon-sidekiq is starting................
Attention : 197146 Please wait, the service mastodon-streaming is starting.................
```

If I recall correctly this is expected, but what is it doing exactly?
It should give a bit more feedback so that we can estimate when it will end. It’s been several hours already I think.

**Comment by MCMic** [comment]
It seems it was just the backup, any idea why the backup takes so much time? What does it backup, can I control this? (I do not need a backup of my whole mastodon history)

**Comment by yalh76** [comment]
It backup all mastodon: application + datas. to be able to restore it from scratch

**Comment by MCMic** [comment]
> It backup all mastodon: application + datas. to be able to restore it from scratch

Why does it take so long? Why is there no feedback? Is it configurable?
