### ISSUE TITLE
Taking backup 

### ISSUE THREAD

**Issue by Vibhigupta** [YunoHost-Apps/mastodon_ynh#219]
I messed up yunohost installation although mastodon is still accessible, I wanted to take backup of DB.

Can you tell me how can I take backup of the mastodon instance DB?

**Comment by Vibhigupta** [comment]
@yalh76 
Can you help regarding the DB backup only via cmd? I have take the backup using` pg_dump mastodon_production > backup.dump `

But I am not able to import it, there must be some issue with DB can you please help me, to backup DB right way.

**Comment by yalh76** [comment]
It's better to make a full backup of mastodon doing: `yunohost backup create --apps mastodon`
You will be able to make a full restore on another Yunohost

**Comment by Vibhigupta** [comment]
Thank You,

The instance was preety new and was not open for registration.  So I have created a new instance without yunohost as I was getting weird error regarding python before the mess happened . So taken a decesion to run without yunohost. 😿

Thank you
