### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by otrapersona** [YunoHost-Apps/mastodon_ynh#232]
Thanks for your work on bringing Mastodon to YunoHost, it is very appreciated.

Since the current version 3.1.2 there has been at least 5 security fixes (as well as many, many non-security fixes and/or changes).

I respectfully ask for the app to be kept more up to date for security reasons and since users see people from other instances enjoying new features and ask for them.

**Comment by yalh76** [comment]
The problem is => https://github.com/YunoHost-Apps/mastodon_ynh/pull/209#commitcomment-38370166
If you have a solution to install Redis 4 on stretch, feel free to do a PR ^^

**Comment by otrapersona** [comment]
As predicted by https://github.com/YunoHost-Apps/mastodon_ynh/pull/209#commitcomment-38397314 the problem has been solved for the current and future versions of Buster-based Yunohost, where the redis verison is 5.0.3. :)
