### ISSUE TITLE
Another issue in the upgrade from stretch to buster

### ISSUE THREAD

**Issue by noccio** [YunoHost-Apps/mastodon_ynh#236]
I have an issue from the migration from stretch to buster.

In my error.log I see

`2020/08/28 17:16:05 [error] 2883#2883: *12616 connect() failed (111: Connection
refused) while connecting to upstream, client: 95.216.40.49, server: mastodon.cybervalley.org, request: "POST /inbox HTTP/1.1", upstream: "http://127.0.0.1:3000/inbox", host: "mastodon.cybervalley.org"`

If I try to restart the mastodon-streaming service I get this error:

`● mastodon-streaming.service - mastodon-streaming
   Loaded: loaded (/etc/systemd/system/mastodon-streaming.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-08-28 11:40:22 CEST; 5h 38min ago
 Main PID: 30491 (node)
    Tasks: 18 (limit: 4483)
   Memory: 42.6M
   CGroup: /system.slice/mastodon-streaming.service
           ├─30491 /opt/node_n/n/versions/node/10/bin/node ./streaming
           └─31472 /opt/node_n/n/versions/node/10.21.0/bin/node /var/www/mastodon/live/streaming

Aug 28 15:40:23 cybervalley.org systemd[1]: /etc/systemd/system/mastodon-streaming.service:11: Invalid environment assignment, ignoring: __YNH_LOAD_NODE_PATH__
Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.`

The other services are working fine.

**Comment by yalh76** [comment]
Should be fixed by https://github.com/YunoHost-Apps/mastodon_ynh/pull/249
