### ISSUE TITLE
Enhancement: tootctl

### ISSUE THREAD

**Issue by azbulutlu** [YunoHost-Apps/mastodon_ynh#237]
Right now a new user has to add the Rails_env production manually to the active run and then add it to the .bashrc manually,
then add the mastodon/live path to the existing paths to be able to use tootctl from command line. 

While most of this are in the mastodon docs, these are several fiddly items to access a tool that is used regularly when maintaining the mastodon server, which might not be as easy to manage for a user with less tech experience. 

Would it be feasible to make this setup part of the install or at least part of the instructions for the installation?

**Comment by nin0-0** [comment]
my install still can't find the ruby installation
```bash
RAILS_ENV=production bin/tootctl help
/usr/bin/env: ‘ruby’: No such file or directory

**Comment by ImaCrea** [comment]
stuck here also but can't find how to fix it :/
please help 🙏 
for your reference: https://forum.yunohost.org/t/souci-de-federation-mastodon/13679/2

**Comment by ImaCrea** [comment]
yay!
