### ISSUE TITLE
Fatal error while trying to install Mastodon on Raspberry Pi 4

### ISSUE THREAD

**Issue by narFnarF** [YunoHost-Apps/mastodon_ynh#240]
Note: This is a copy of : https://github.com/YunoHost/issues/issues/1668

I attempted to install Mastodon on my Yunohost and got a fatal error. I'm reporting the error here as the app suggested me to do.

Screenshot of the error:
![](https://i.imgur.com/Sde0TVs.png)

Paste of the error:
https://paste.yunohost.org/raw/yewivizido

My device:
- Raspberry Pi 4
- 4GB of Ram
- Freshly installed Yunohost last week
- Other installed apps on the same device: Bibliogram, RoundCube, Discourse

I'm very new to Yunohost but I find it very cool so far. Don't hesitate to ask for more infos. I'll help as much as I can.

**Comment by alexAubin** [comment]
Indeed, these days many people report that same issue about bcrypt failing to compile

```
2020-10-20 00:21:10,435: WARNING - current directory:
2020-10-20 00:21:10,436: WARNING - /var/www/mastodon/live/vendor/bundle/ruby/2.6.0/gems/bcrypt-3.1.13/ext/mri
2020-10-20 00:21:10,437: WARNING - make "DESTDIR="
2020-10-20 00:21:10,439: WARNING - compiling bcrypt_ext.c
2020-10-20 00:21:10,440: WARNING - compiling crypt_blowfish.c
2020-10-20 00:21:10,441: WARNING - gcc  -D__SKIP_GNU -I/opt/rbenv/versions/2.6.6/include  -D_FILE_OFFSET_BITS=64
2020-10-20 00:21:10,442: WARNING - -c -o x86.o x86.S
2020-10-20 00:21:10,444: WARNING - x86.S: Assembler messages:
2020-10-20 00:21:10,445: WARNING - x86.S:202: Error: junk at end of line, first unrecognized character is `,'
2020-10-20 00:21:10,446: WARNING - make: *** [<builtin>: x86.o] Error 1
[...]
2020-10-20 00:21:10,458: WARNING - An error occurred while installing bcrypt (3.1.13), and Bundler cannot continue.
2020-10-20 00:21:10,459: WARNING - Make sure that `gem install bcrypt -v '3.1.13' --source 'https://rubygems.org/'`
2020-10-20 00:21:10,460: WARNING - succeeds before bundling.
```

I'm really not knowledgeable enough about this app and ruby to know how to fix it tho, maybe the people maintaining the app know better :/

**Comment by nr458h** [comment]
Hi even so I run on normal on x86 architecture, I'm unable to install mastodon.

Der Vorgang konnte nicht abgeschlossen werden 'Installiere die Anwendung 'mastodon''. Bitte gib das vollständige Protokoll dieser Operation mit Klicken Sie hier an, um Hilfe zu erhalten

The logs are uploaded to [Yunohost Paste](https://paste.yunohost.org/raw/ehumululum)
If this is not related to the ARM-error I would create a new issue.

Thanks in advance

**Comment by fh2006** [comment]
Hi!
This issue can be fixed by adding the lines with „bcrypt“ to /scripts/install:
`#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..."

ynh_app_setting_set --app=$app --key=final_path --value=$final_path
# Download, check integrity, uncompress and patch the source from app.src
mkdir $final_path

if [ "$(lsb_release --codename --short)" = "buster" ]; then
    ynh_setup_source --dest_dir="$final_path/live"
    #add the line below this comment
    ynh_replace_string --match_string="bcrypt (3.1.13)" --replace_string="bcrypt (3.1.14)" --target_file="$final_path/live/Gemfile.lock"
else
    ynh_script_progression --message="Setting up source files..."

    ynh_setup_source --dest_dir="$final_path/live" --source_id=jessie

    # Temporary workaround for https://github.com/tootsuite/mastodon/issues/13292
    ynh_replace_string --match_string="sidekiq-unique-jobs (6.0.18)" --replace_string="sidekiq-unique-jobs (6.0.20)" --target_file="$final_path/live/Gemfile.lock"
    #add the line below this comment
    ynh_replace_string --match_string="bcrypt (3.1.13)" --replace_string="bcrypt (3.1.14)" --target_file="$final_path/live/Gemfile.lock"
fi `

**Comment by fh2006** [comment]
Hi!
This issue can be fixed by adding the lines with „bcrypt“ to /scripts/install:
`ynh_script_progression --message="Setting up source files..."

ynh_app_setting_set --app=$app --key=final_path --value=$final_path
# Download, check integrity, uncompress and patch the source from app.src
mkdir $final_path

if [ "$(lsb_release --codename --short)" = "buster" ]; then
    ynh_setup_source --dest_dir="$final_path/live"
    #add the line below this
    ynh_replace_string --match_string="bcrypt (3.1.13)" --replace_string="bcrypt (3.1.14)" --target_file="$final_path/live/Gemfile.lock"
else
    ynh_script_progression --message="Setting up source files..."

    ynh_setup_source --dest_dir="$final_path/live" --source_id=jessie

    # Temporary workaround for https://github.com/tootsuite/mastodon/issues/13292
    ynh_replace_string --match_string="sidekiq-unique-jobs (6.0.18)" --replace_string="sidekiq-unique-jobs (6.0.20)" --target_file="$final_path/live/Gemfile.lock"
    #add the line below this
    ynh_replace_string --match_string="bcrypt (3.1.13)" --replace_string="bcrypt (3.1.14)" --target_file="$final_path/live/Gemfile.lock"
fi `

**Comment by fh2006** [comment]
Hi!
This issue can be fixed by using the install file attached to this comment.
In the Script I added two lines in the „ DOWNLOAD, CHECK AND UNPACK SOURCE“ section.
[install](https://github.com/YunoHost-Apps/mastodon_ynh/files/5549456/install.txt)

**Comment by nr458h** [comment]
As I don't know how I could make this work with the provided workaround - will these changes also come to the master branch?
