### ISSUE TITLE
404 on headers / avatars of remote media

### ISSUE THREAD

**Issue by nin0-0** [YunoHost-Apps/mastodon_ynh#244]
```bash
Nov 12 07:03:08 <domain> bundle[28660]: [005ffae0-808f-43c2-ac3f-c1bf84f832f6] method=GET path=/system/cache/accounts/headers/000/007/582/original/5f9a3eb804794604.png format=png controller=ApplicationController action=raise_not_found status=404 duration=5.33 view=0.72 db=1.02
```

I get many 404's on avatars and headers of remote accounts. I run the rake to remove remote content daily to avoid the disk filling up. I've temporarily disabled it to see if this resolves the issue. Though I thought that remote media is refetched when not available, when requested.

2 examples of not fetched remote media URI:
`system/cache/accounts/headers/`
`system/accounts/avatars/`

In nginx.conf I see:
```bash
location ~ ^/(emoji|packs|system/accounts/avatars|system/media_attachments/files) {
  more_set_headers "Cache-Control: public, max-age=31536000, immutable";
  more_set_headers "Strict-Transport-Security: max-age=31536000";
  try_files $uri @proxy;
}
```
Should cache be added here?

**Comment by yalh76** [comment]
Did you tried with last mastodon version ?
