### ISSUE TITLE
Import account from a database not managed by Yunohost

### ISSUE THREAD

**Issue by csolisr** [YunoHost-Apps/mastodon_ynh#245]
I'm currently using a bare-metal installation of Mastodon, but would like to migrate to Mastodon. However, I'm not sure if it's possible to use my PostgreSQL database backup to import the data from my old account into the new account automatically generated by Mastodon, especially the old toots that can't be imported directly via the web interface.

**Comment by yalh76** [comment]
Maybe should ask at mastodon forum who to restore data of a mastodon instance
