### ISSUE TITLE
Update broke my instances

### ISSUE THREAD

**Issue by Ternoc** [YunoHost-Apps/mastodon_ynh#248]
I updated all my applications and my server and now I have a generic error message whenever I go to my instance.
![image](https://user-images.githubusercontent.com/11840322/102017317-932b9e80-3d66-11eb-86d1-d599155081fa.png)

**Comment by adidal** [comment]
@Ternoc ahah same

both Mastodon-sidekiq and Mastodon-web are stuck in a bootloop.

Here's what j[ournalctrl gives me in return.](https://gist.github.com/adidal/bbee64afe732cf604fa3b1cdff1876e2)

**Comment by adidal** [comment]
Today's update solved this issue :)
