### ISSUE TITLE
armv7l - Unable to install mastodon

### ISSUE THREAD

**Issue by punkrockgirl** [YunoHost-Apps/mastodon_ynh#257]
Hi,
I'm trying to install Mastodon on a **Raspberry Pi 4**. I believe it should now be compatible with ARM, correct me if I'm wrong.

However, each time that I run the command (terminal) or use the GUI the install fails.

YunoHost freshly installed and updated to the last available version.

Here is the log: https://paste.yunohost.org/raw/rejuhukolo

Thanks

**Comment by rosbeef** [comment]
hi same error here:
https://paste.yunohost.org/raw/egakubaneb

**Comment by lightnin** [comment]
Same error here: https://paste.yunohost.org/raw/egakubaneb

**Comment by yalh76** [comment]
All errors are the same, related to bcrypt
Can you try to install mastodon 3.3 doing `yunohost app install https://github.com/YunoHost-Apps/mastodon_ynh/tree/upgrade` and let me know if it solves the issue

**Comment by punkrockgirl** [comment]
I can confirm that it works.

It took ~50 mins on a Raspberry Pi 4B, 2 Gb RAM.
Yunohost version: 4.1.7.2

If anyone is interested, here is the log: https://paste.yunohost.org/raw/iyipolipoh

My question now: in the future, is it possible to migrate to the stable/non-testing branch without uninstalling and installing again?

**Comment by yalh76** [comment]
> My question now: in the future, is it possible to migrate to the stable/non-testing branch without uninstalling and installing again?

There won't be any migration, when 3.3 will be in the master branch your install will be updated to last master branch (stable version)

**Comment by punkrockgirl** [comment]
Thanks, all clear now!
