### ISSUE TITLE
Won't install (Not sure what happend)

### ISSUE THREAD

**Issue by VelocityDesign** [YunoHost-Apps/mastodon_ynh#265]
### Describe the bug
I just get an error about installation.
### Context

- Hardware: Hostinger VPS 1
- YunoHost version: 4.1.8
- I have access to my server: SSH & Webpanel
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain:
- Using, or trying to install package version/branch: master/main

### Steps to reproduce
    ```sh
    sudo yunohost app install mastodon
    ```
or webpanel equivalent
### Expected behavior
YH installs mastodon correctly.

### Logs
https://paste.yunohost.org/raw/elavefahik

**Comment by yalh76** [comment]
Seems like you VPS doesn't allow swap : you should check that
```
2021-04-18 05:00:23,466: WARNING - swapon: /swap_mastodon: swapon failed: Operation not permitted
```
