### ISSUE TITLE
Install fail in 4.2 : $RBENV_ROOT should be $rbenv_root ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/mastodon_ynh#270]
`2021-05-09 13:21:20,131: WARNING - Variable $rbenv_root wasn't initialized when trying to replace __RBENV_ROOT__ in /etc/systemd/system/mastodon-web.service`

In 4.1 apparently the mechanism relied on --other_vars but this ain't used anymore ...

Corresponding line: https://github.com/YunoHost-Apps/mastodon_ynh/blob/master/scripts/ynh_install_ruby__2#L14

**Comment by adrienlacombe** [comment]
Même soucis ici
