### ISSUE TITLE
Removing old cache items?

### ISSUE THREAD

**Issue by binarydad** [YunoHost-Apps/mastodon_ynh#278]
### Describe the bug

Old cache item (images, etc) are not removed. I have items from my original installation back in November 2020 in the /var/www/mastodon/live/public/system/cache/media_attachments/ directory. Should there be a process to remove these, either manually or automatically?

### Context

- Hardware: VM Guest
- YunoHost version: 4.2.4
- I have access to my server: SSH, web

**Comment by yalh76** [comment]
If you find something in mastodon documentation, you can try to do a PR :)

**Comment by azbulutlu** [comment]
Mastodon admin tools do come with some command lines to remove old media older than certain number of days. 
https://docs.joinmastodon.org/admin/tootctl/#media

they do require setting a cron job or use SSH but then again it does required going into the command line to use. (not sure why they are not available on front-end)
