### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by tbalthazar** [YunoHost-Apps/mastodon_ynh#28]
Hi,

I did a fresh install of Yunohost 2.5.6 on Debian 8 on a X86-64 Scaleway server.
I installed a few apps successfully, but when I try to install Mastodon via the Yunohost admin web UI, I get this in `/var/log/yunohost/yunohost-api.log`:
https://paste.nolog.computer/?c016c4b8e8676a22#BmiprpO3dZrvykxIR6Jhavp0lEsDDGNzrMEHQjFimxw=

How can I help debug this?

Thanks!
Thomas.

**Comment by tbalthazar** [comment]
And via the command line, it gives:
```
root@xx:/var/log# yunohost app install https://github.com/YunoHost-Apps/mastodon_ynh
Available domains:
- example.com
- example.org
Choose a domain for Mastodon (default: example.com) example.org
Choose the Mastodon administrator (must be an existing YunoHost user): username
Enter password of this administrator ≥ 8 character:
Choose the application language [en_EN | fr_FR] (default: fr_FR): en_EN
Error: An unexpected error occured
Warning: No passwd entry for user 'postgres'
Warning: No passwd entry for user 'postgres'
Warning: /opt/mastodon doesn't deleted because it's not exist.
Warning: /etc/cron.d/mastodon doesn't deleted because it's not exist.
Warning: /etc/apt/sources.list.d/backports.list doesn't deleted because it's not exist.
Warning: /etc/apt/sources.list.d/yarn.list doesn't deleted because it's not exist.
Warning: /usr/bin/ruby doesn't deleted because it's not exist.
Warning: userdel: user 'mastodon' does not exist
Error: Installation failed
```

**Comment by nemsia** [comment]
I try same settings on my test server.

**Comment by nemsia** [comment]
You can try with this command:
yunohost app install https://github.com/YunoHost-Apps/mastodon_ynh --verbose

**Comment by tbalthazar** [comment]
Looks like it worked this time.
The only thing I did differently (besides the `--verbose` flag) is that I chose a simple ascii password instead of a complex password, which was:
```
e;7EVk,_t9huj}=W;t~B5.4i=?`k9Vf/
```
Maybe that's the issue?

**Comment by nemsia** [comment]
--verbose add just more details in log.
It's good test with this password, you can modify it after install.
I will check this.

Thanks.

**Comment by nemsia** [comment]
Yes, this password make same error on my server.

**Comment by nemsia** [comment]
All work to you ?

**Comment by tbalthazar** [comment]
With the complex password, the installation process fails.
With a simple ASCII password, it works.
So I guess the problem was indeed the password that wasn't escaped correctly at some point.
Thanks! :)
