### ISSUE TITLE
restoring backup fails

### ISSUE THREAD

**Issue by morta5** [YunoHost-Apps/mastodon_ynh#283]
### Describe the bug

I ran a command to restore mastodon from an upgrade-backup because upgrading failed(there was an apt error I already fixed) but restoring fails 

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 4.2.5.2
- I have access to my server: *Through SSH, Webadmin and also physical access if needed *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain:
  - I have installed Adguard Home on my server without the Yunohost package, I have installed some packages manually from apt and I have added some repositories
- Using, or trying to install package version/branch: 
- If upgrading, current package version: 3.2.2~ynh1 

### Steps to reproduce

```
sudo yunohost backup restore 20210624-125956 --apps mastodon 
```

### Logs

https://paste.yunohost.org/raw/enalayituq

**Comment by yalh76** [comment]
There is an issue with one of your source file: it includes `https://ookla.bintray.com/debian` that is not reacheable. You should look at the files in `/etc/apt/sources.list.d/` and remove the corresponding line before doing the restore

**Comment by morta5** [comment]
Thanks! Will try it.

**Comment by morta5** [comment]
Unfortunately I still can't restore the backup. Here are the logs:
https://paste.yunohost.org/raw/esiculatiz

**Comment by weex** [comment]
> Unfortunately I still can't restore the backup. Here are the logs: https://paste.yunohost.org/raw/esiculatiz

Pertinent log error:

`2021-08-03 07:51:10,767: DEBUG - + echo 'Couldn'\''t parse SOURCE_URL from /home/yunohost.backup/tmp/20210624-125956/apps/mastodon/settings/conf/rbenv.src ?'`

If you have the backup file , perhaps opening that up and looking at `rbenv.src` will shed some light on the problem. Logs of when you did the backup might be helpful as well.

**Comment by morta5** [comment]
I will close this for now as I don't need to restore this backup anymore and unpacking the backup would take too long as for some reason it did also backup media files. But thanks for your help :)
