### ISSUE TITLE
App currently level 1 because failing the multi-instance install test uh

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/mastodon_ynh#284]
c.f. https://ci-apps.yunohost.org/ci/job/2348

The first instance can be accessed properly but not the second one: 

```

 > Validating that the app mastodon__2 can/can't be accessed with its URL...

Error: The HTTP code shows an error.
Warning: Test URL: domain.tld
Real URL: https://domain.tld/
HTTP code: 403
Page title: Action Controller: Exception caught
Page extract:
                            Blocked host: domain.tld

To allow requests to domain.tld, add the following to your environment
configuration:

config.hosts << "domain.tld"
```

I'm not super familiar with the app so I don't know where that's to be configured, but sounds like a config file inconsistency somehow

**Comment by Tagadda** [comment]
This append because some dependencies explicitly block `domain.tld` (`sub.domain.tld` still works).
Is there any way to specify another domain for the multi-instance test ?

**Comment by yalh76** [comment]
test disabled ^^
