### ISSUE TITLE
is backuping live_back relevant?

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/mastodon_ynh#286]
Backuping Mastodon can take long because of the size of the generated archive. That's why I ask this question.

When we backup Mastodon, we also archive the `live_back` folder (`/var/www/mastodon/live_back`).

I can't find any documentation of how nor of the usage of this folder. It looks like it's a kind of backup (a copy at some point of the `/var/www/mastodon/live` folder). And if I am not wrong, I wonder if that's relevant to backup this directory?

Thanks in advance for your answer!

**Comment by yalh76** [comment]
As far as i've checked, there is no `live_back` in mastodon. You can delete it

**Comment by fflorent** [comment]
I see, it used to be created before f1ea723f4402b1adff2c393e1e7e207f0b301f7b, and for some reasons, the removal did not run for me.

I remove it, thanks!
