### ISSUE TITLE
Upgrade to 1.4 don't work

### ISSUE THREAD

**Issue by nemsia** [YunoHost-Apps/mastodon_ynh#29]
[Log](https://yunohost.nemsia.org/zerobin/?e5d05b9275af250c#SVLGaQjHbM+YU960v4JbyRVVO79VdtofJTynS+GKFag=)

**Comment by magikcypress** [comment]
Need to upgrade node with version 6 ;)

> postcss-smart-import@0.6.12: The engine "node" is incompatible with this module.

**Comment by magikcypress** [comment]
need test

**Comment by nemsia** [comment]
upgrade fixed to latest stable release : https://github.com/YunoHost-Apps/mastodon_ynh/pull/31
I test 1.4 upgrade on https://github.com/nemsia/mastodon_ynh/tree/fix-upgrade-1.4

**Comment by magikcypress** [comment]
For the moment when I install the application, I have an error calling the assets. While updating the problem is corrected

**Comment by magikcypress** [comment]
fix install with lastest release 79f5e7d
don't update with release candidat
