### ISSUE TITLE
is elasticsearch supported ?

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/mastodon_ynh#319]
Hello, 
i would know how to activate the search system, 
looks like ES is needed: https://docs.joinmastodon.org/admin/optional/elasticsearch/
is mastodon_ynh ready for this ?

thx for your help

**Comment by yalh76** [comment]
elasticsearch is not implement in mastodon_ynh, but feel free to do a PR if you want it.
PS: also think of the Raspberry Pi users ... maybe they won't want elasticsearch ^^
