### ISSUE TITLE
Installation failed on raspberry pi

### ISSUE THREAD

**Issue by Rafi594** [YunoHost-Apps/mastodon_ynh#32]
Hi

I tryed to install mastodon on raspberry pi but the installation fail

The log 

https://paste.yunohost.org/bapisayine.diff

**Comment by nemsia** [comment]
Une erreur GPG, je regarderai ça bientôt avec un serveur scaleway.
Merci.

21 mai 2017 19:57 "Rafi59"  a écrit:
	Hi 

	I tryed to install mastodon on raspberry pi but the installation fail 

	The log 

	https://paste.yunohost.org/bapisayine.diff (https://paste.yunohost.org/bapisayine.diff)

**Comment by nemsia** [comment]
You have raspberry 1, 2 or 3 ?
I can't reproduce on Scaleway, arm64 CPU...

**Comment by Rafi594** [comment]
I have a raspberry pi  3

**Comment by nemsia** [comment]
At this time this package can't work ARM raspberry,
i will try soon as possible to work on it.

**Comment by magikcypress** [comment]
thanks guys for you report ;)
i think we must follow this bug https://github.com/tootsuite/mastodon/issues/1250
