### ISSUE TITLE
Cannot change email?

### ISSUE THREAD

**Issue by binarydad** [YunoHost-Apps/mastodon_ynh#323]
### Describe the bug

When attempting to change my email, I go to the /auth/edit page, type in the new email I want, along with my current password, and click Save Changes. The result is the error message below. I'm not sure if this is intentional, or if it's related to the SSO features of Yunohost. The password is surely correct in this case. 

![image](https://user-images.githubusercontent.com/1760607/165660454-4c06cd9d-9c53-42b1-81a2-60d4f0cce62b.png)

### Context

I am using Mastodon 3.5.1 installed via Yunohost 4.3.6.3 on Debian 10.

**Comment by Tagadda** [comment]
You can't change the mail as it's provided by the LDAP and is related to the SSO.

**Comment by binarydad** [comment]
Got it, thank you. If I change my email for my user in the YNH console, will it cause issues?

![image](https://user-images.githubusercontent.com/1760607/165765244-92b2aa39-f695-4697-a343-2e10389629d2.png)

**Comment by Tagadda** [comment]
I don't know for sure. Maybe there's no issue, in any case you can undo the change.

**Comment by przemyslawwilde** [comment]
> ### Describe the bug
> 
> When attempting to change my email, I go to the /auth/edit page, type in the new email I want, along with my current password, and click Save Changes. The result is the error message below. I'm not sure if this is intentional, or if it's related to the SSO features of Yunohost. The password is surely correct in this case.
> 
> ![image](https://user-images.githubusercontent.com/1760607/165660454-4c06cd9d-9c53-42b1-81a2-60d4f0cce62b.png)
> ### Context
> 
> I am using Mastodon 3.5.1 installed via Yunohost 4.3.6.3 on Debian 10.

Good evening
I also have this problem. I received a message that my password is incorrect. Is there any way to change it?
I can log in to my account correctly, but I can't change my password because I'm getting the information that it is incorrect.

![mastodon](https://user-images.githubusercontent.com/5512707/200198905-429c6082-0800-4f4f-93c2-4d0b72182fe7.png)

Mastodon | 3.5.3 on Debian 11 | YunoHost 11.0.10.2 (stable)
