### ISSUE TITLE
How to enable 2FA for Admin account?

### ISSUE THREAD

**Issue by Zeitverschreib** [YunoHost-Apps/mastodon_ynh#330]
- Hardware: Yunohost VM on NAS
- YunoHost version: 3.5.3
- I have access to my server: *Through SSH | through the webadmin | 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no"
 
When trying to enable 2FA for the Admin account, the panel asks for the current pw, but the current and verified pw for the yunohost_user = Admin is not accepted.

What is the correct procedure for enabling 2FA in this scenario?

Thanks in advance.

**Comment by yalh76** [comment]
not sure it's possible to enable 2FA as authentication is made on ldap
