### ISSUE TITLE
 Upgrade to 3.5.3~ynh2 seems to have broken hashtags and bookmarks

### ISSUE THREAD

**Issue by Zeitverschreib** [YunoHost-Apps/mastodon_ynh#333]
Since the upgrade to 3.5.3 ynh2, I keep getting error messages when 

a) trying to open my list of bookmarks
b) clicking on hashtags in post

"Etwas ist beim Laden schiefgelaufen." in the right section.

"Hoppla!Ein unerwarteter Fehler ist aufgetreten." as banner in the bottom left of the page.

**Comment by Zeitverschreib** [comment]
The problem is still there, but in the mean time I found out that it seems to be browser related.

On Safari, Edge and Fennec (Android), css and javascript does not work/load. On Chromium (Linux( and Chrome (Windows 10), the site loads correctly, bookmarks and tags work.

Has there been any change in browser detection?

**Comment by Zeitverschreib** [comment]
I just updated to yhn3, still the same problem.

Just  an example, loading the sign-in page in Chromium as standard tab and incognito gives to different layouts:

![image](https://user-images.githubusercontent.com/106703972/174043920-bc51a967-bbc3-4def-b577-389336014ce2.png)

![image](https://user-images.githubusercontent.com/106703972/174044064-02252872-d22a-4c7e-bbc1-e3d9be99fe01.png)

In Chromium standard tab, the whole site works. In Firefox standard tab, following hashtags and/or going to bookmarks gives an error.

![image](https://user-images.githubusercontent.com/106703972/174044974-48087c67-f7c0-46b7-9835-59b73d600980.png)

**Comment by binarydad** [comment]
I've noticed I'm getting a lot of 404 from static assets. 

https://paste.yunohost.org/emilerazud

**Comment by binarydad** [comment]
Well, I WAS having 404 issues just now, but running `sudo yunohost app upgrade mastodon -F` to force reinstall worked. In looking at your 2nd screenshot, it looks like a CSS link wasn't loading, resulting in the huge/unstyled logo. Not sure if related though to the original issue.

**Comment by Zeitverschreib** [comment]
The -F solved the problem, everything seems to be working again.  I tested in Firefox, Chromium and LibreWolf.

Thanks for your help.
