### ISSUE TITLE
Logging out of Mastodon redirects user to yunohost login screen

### ISSUE THREAD

**Issue by 0utl4w** [YunoHost-Apps/mastodon_ynh#336]
Hardware: VPS on gandi.net
Server access: SSH, webadmin
No tewaks on yunohost instance
Using mastodon_ynh 3.5.3

Hi there, I installed mastodon (publicly) on ynh by using the webadmin interface. Since the beginning I have the annoying behaviour that when a user loggs out of mastodon they get redirected to the yunohost sso login page (https://domain.tld/yunohost/sso/) and not the welcomepage (https://social.domain.tld/). 

Is there a way change this behaviour?

**Comment by Tagadda** [comment]
This behaviour is a side effect from the SSO logout mechanism.
When you log in from YunoHost SSO, and try to access Mastodon, you're automatically logged in. When you log out from Mastodon, you're redirected to the logout page of the SSO and then redirected back to the login form.

[This patch](https://github.com/YunoHost-Apps/mastodon_ynh/blob/master/sources/patches/app-sso.patch#L8-L11) modify the redirect URL after the logout.

**Comment by 0utl4w** [comment]
Thanks for the quick reply  but that happens also to users that are not yunohost users.

----------------------------------------

20.08.2022 19:01:00 Tagada ***@***.***>:

**Comment by Tagadda** [comment]
Yes, the path modify the URL any user get redirected to on a Mastodon logout.
So every users get redirected to the YunoHost login page, even if they did not log on from there.

While we implement this in the package, you could reverse this patch by editing the file directly.
You'll have to edit the file at `/var/www/mastodon/live/app/controllers/application_controller.rb` near line 71 and replace the whole line with the URL with `new_user_session_path`, so the function is exactly this : 
```rb
   def after_sign_out_path_for(_resource_or_scope)
     new_user_session_path
   end
```
And then run `sudo systemctl restart mastodon-web` to restart the mastodon service.

**Comment by 0utl4w** [comment]
Great, I'll give it a try. Thanks a lot.

----------------------------------------

20.08.2022 19:20:13 Tagada ***@***.***>:

**Comment by GoodReese** [comment]
> Yes, the path modify the URL any user get redirected to on a Mastodon logout. So every users get redirected to the YunoHost login page, even if they did not log on from there.
> 
> While we implement this in the package, you could reverse this patch by editing the file directly. You'll have to edit the file at `/var/www/mastodon/live/app/controllers/application_controller.rb` near line 71 and replace the whole line with the URL with `new_user_session_path`, so the function should be exactly this :
> 
> ```ruby
>    def after_sign_out_path_for(_resource_or_scope)
>      new_user_session_path
>    end
> ```
> 
> And then run `sudo systemctl restart mastodon-web` to restart the mastodon service.
> 
> EDIT: This manual modification will be undone by the upgrade script, so you'll have to do it again after an upgrade until this is implemented in the package.

Thank you, finally solved my issue, hope there will add a new toggle button in yunohost admin panel ~
