### ISSUE TITLE
Installation failed BUILD FAILED 

### ISSUE THREAD

**Issue by Rafi594** [YunoHost-Apps/mastodon_ynh#34]
Hi

I tryed to install mastodon in a virtual machine (virtualbox) but the build of ruby failed

I have used a local domain other than the principal
The log
https://framabin.org/?d5c0ae83b6ff72b1#nf8hry9fw7eOlSf0cmxXCazh4og7bcVQxwPR8Kt/Vqs=

Thanks for your help

**Comment by magikcypress** [comment]
Add more space into /tmp 

> Attention : /tmp/ccP3CPcZ.s: Erreur fatale: ne peut écrire ossl_asn1.o: Aucun espace disponible sur le périphérique

**Comment by nemsia** [comment]
Need more ram or swap to install (1Go min.)
