### ISSUE TITLE
Cant install on a fresh system

### ISSUE THREAD

**Issue by harcesz** [YunoHost-Apps/mastodon_ynh#343]
### Describe the bug

Mastodon wont install

### Context

- Hardware: VPS bought online, debian bullseye
- YunoHost version: current
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain:
- Using, or trying to install package version/branch: any mastodon

### Steps to reproduce

- attempt to install mastodon

### Expected behavior

Mastodon should install

### Logs

On my server with other apps cant compile Ruby 3.0.3 which seems to be a problem in itself on Debian Bullseye. Got a separate VPS just to test it out, some progress but still fails; https://paste.yunohost.org/raw/ipucedecig 

At least one other person on the Matrix channel confirmed the problem. This is pretty bad, at a time when a ton of people are moving to Mastodon.

**Comment by alexAubin** [comment]
>FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

Sounds like it's "just" your system running out of RAM ?

**Comment by harcesz** [comment]
Well paint me blue and call me birdie, increasing the RAM solved the problem. It just wont compile on less than 2GB or RAM.

**Comment by christ-offer** [comment]
I've been trying to install myself, but not getting any verbose enough errors to figure out why it fails over here, both webadmin and ssh: https://paste.yunohost.org/raw/fusuxajefe

**Comment by yalh76** [comment]
> Well paint me blue and call me birdie, increasing the RAM solved the problem. It just wont compile on less than 2GB of RAM.
> 
> Does everything need to be compiled for this app? Could it at least provide some clear indication as to the reason of fail or required resources? (This log was far more informative than earlier ones).

Yes everything need to be compiled, as written in the documentation => https://docs.joinmastodon.org/admin/install/

**Comment by yalh76** [comment]
> I've been trying to install myself, but not getting any verbose enough errors to figure out why it fails over here, both webadmin and ssh: https://paste.yunohost.org/raw/fusuxajefe

should also be some RAM issue, how many do your server have ?

**Comment by christ-offer** [comment]
> > I've been trying to install myself, but not getting any verbose enough errors to figure out why it fails over here, both webadmin and ssh: https://paste.yunohost.org/raw/fusuxajefe
> 
> should also be some RAM issue, how many do your server have ?

Im running it on the 2gb RAM shared VPS at linode atm. Is that too little if im also running nextcloud and calibre there?
