### ISSUE TITLE
No edit option on posts

### ISSUE THREAD

**Issue by thebongmaster** [YunoHost-Apps/mastodon_ynh#346]
I have no Edit option on any posts on my install. 

Raspberry Pi4, Standard YunoHost image, Standard Mastodon app V3.5.3
No other apps installed.

**Comment by StefOfficiel** [comment]
Hi! Editing messages is only available in Mastodon V.4.0.2 which is coming soon on YunoHost! #345

**Comment by Tagadda** [comment]
Closed by #350
