### ISSUE TITLE
Migration to another instance is impossible

### ISSUE THREAD

**Issue by svenbrier** [YunoHost-Apps/mastodon_ynh#349]
The "Move to another account" feature does not work. After pressing the button, the specification of an incorrect password is criticized. The password is correct, but the execution of the function is repeatedly rejected. The Version is 3.5.3~ynh4.

**Comment by memo-567** [comment]
Maybe this solution will also work for Mastodon:

https://forum.yunohost.org/t/glitch-soc-mastodon-ldap-conflict/17230/2

I'm not sure if this will work, so it's probably better to make a backup beforehand.

**Comment by panomaki** [comment]
I assume (which I know you should never do) that the moving is prevented from LDAP authentication indeed. After all, if you have a local (LDAP)account, you probably want to use more services and therefor aren't really wanting to move.

Then, there may be use cases. I have a configuration option for switching on/off LDAP-authentication on Mastodon (in env.production) via the yunohost configuration interface on my wishlist... That may make this easier to solve.

**Comment by svenbrier** [comment]
> Maybe this solution will also work for Mastodon:
> 
> https://forum.yunohost.org/t/glitch-soc-mastodon-ldap-conflict/17230/2
> 
> I'm not sure if this will work, so it's probably better to make a backup beforehand.

Thanks for your tip. I was now able to redirect the account to the new instance. However, moving the account did not work.

**Comment by memo-567** [comment]
I suspect that the "`an incorrect password is criticized`" message is because your account on Mastodon is an LDAP account.

Disabling LDAP could  help.

Or maybe it's better to wait for @panomaki to make the changes `¯\_(ツ)_/¯`

**Comment by svenbrier** [comment]
I'm happy with the redirect for now. I think I'll try to move again when @panomaki has made the customization built in. Many thanks for your help.

**Comment by yalh76** [comment]
did we keep that issue opened ?

**Comment by Salamandar** [comment]
I can't migrate even with the LDAP disabled :( I actually can't change my password either…
