### ISSUE TITLE
V4: what is the best way to increase max character in a toot ? node.js should be upgraded

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/mastodon_ynh#352]
### Describe the bug

i'm trying to increase the max character in a toot setting.
i followed this link: https://www.draklyckan.se/2021/11/how-to-increase-the-character-limit-for-toots-in-mastodon/

But when i need to run the step `6. Enter the live directory and recompile Mastodon` (afer adapted the command)
i have this error: 
```
yarn install v1.22.19
[1/6] Validating package.json...
error @mastodon/mastodon@: The engine "node" is incompatible with this module. Expected version ">=14". Got "6.17.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Webpacker requires Node.js ">=10.17.0" and you are using v6.17.1
Please upgrade Node.js https://nodejs.org/en/download/
Exiting!
```
### Context

- Hardware: 
VPS bought online
- YunoHost version:
```
yunohost: 
  repo: stable
  version: 11.0.10.2
yunohost-admin: 
  repo: stable
  version: 11.0.11
moulinette: 
  repo: stable
  version: 11.0.9
ssowat: 
  repo: stable
  version: 11.0.9
  ```
- I have access to my server: 
Through SSH && through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: 
no
- mastodon_ynh version:
`version: 4.0.2~ynh1`

### Steps to reproduce

- i follow steps 1 to 5 of https://github.com/YunoHost-Apps/mastodon_ynh
- at step 6, i adapted the command as like (in deduction of what is said in https://github.com/YunoHost-Apps/mastodon_ynh/blob/master/README.md ) : 
`sudo -u mastodon RAILS_ENV=production /opt/rbenv/versions/mastodon/bin/bundle exec rails assets:precompile`

but is is failing with this error: 
```
yarn install v1.22.19
[1/6] Validating package.json...
error @mastodon/mastodon@: The engine "node" is incompatible with this module. Expected version ">=14". Got "6.17.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Webpacker requires Node.js ">=10.17.0" and you are using v6.17.1
Please upgrade Node.js https://nodejs.org/en/download/
Exiting!
```

### Expected behavior

i would the mastodon recompilation is OK with the max characters increased for all toots (in the web browser AND in tusky)

Thx for your help

**Comment by isAAAc** [comment]
the max character toots works only in tusky, not in the webapp :thinking:

**Comment by yalh76** [comment]
you should ask at Mastodon repository

**Comment by isAAAc** [comment]
i'll use WriteFreely for long post ;)

**Comment by nschiwy** [comment]
@isAAAc did you ever get this resolved? I recently set up a new Mastodon instance using yunohost and was following a similar guide but am also experiencing the issue with the web not updating while the API (and therefore apps) allowing the longer character limit.
