### ISSUE TITLE
Mastodon broken after update

### ISSUE THREAD

**Issue by dbflexi** [YunoHost-Apps/mastodon_ynh#356]
--- 

### Describe the bug

*Update fails*
When I'm trying to update, it ends with an error (see log below). YH is not able to restore mastodon so the mastodon instance is broken after the update. I restored a snapshot I've done before, so it is working again. But if I try to update again, the same error occurs. 
There are only 2 apps at the yh server: Mastodon and Friendica. No other updates are available.

### Context

- Hardware: *Rootserver bought online*
- YunoHost version: 11.0.10.2
- I have access to my server: *Through SSH | through the webadmin*
- If upgrading, current package version: *3.5.3~ynh4`*

### Logs
https://paste.yunohost.org/raw/jojejugumu

**Comment by yalh76** [comment]
not an upgrade issue but a mastodon install issue, follow at #357
