### ISSUE TITLE
Cannot install on new instance

### ISSUE THREAD

**Issue by BishopGreer** [YunoHost-Apps/mastodon_ynh#357]
### Describe the bug

* Trying to install Mastodon on new Yunohost instance and new server. Gives error and rolls back. 

### Context

Intel 2x with 12 cores and 12 GB ram, 1 TB HD

env:
  YNH_APP_ARG_ADMIN: bishop
  YNH_APP_ARG_DOMAIN: maindomain.tld
  YNH_APP_ARG_IS_PUBLIC: '0'
  YNH_APP_ARG_LANGUAGE: en_EN
  YNH_APP_BASEDIR: /var/cache/yunohost/app_tmp_work_dirs/app_8ui18eyx
  YNH_APP_ID: mastodon
  YNH_APP_INSTANCE_NAME: mastodon
  YNH_APP_INSTANCE_NUMBER: '1'
  YNH_APP_MANIFEST_VERSION: 4.0.2~ynh1
  YNH_ARCH: amd64
error: An error occurred inside the app installation script
interface: api
operation: app_install
parent: null
related_to:
- - app
  - mastodon
started_at: 2022-12-28 08:37:28.317419
success: false
yunohost_version: 11.0.10.2

### Steps to reproduce

Going thru web interface and clicking on install Mastodon in the application list. 

### Expected behavior

*It should install. 

### Logs

* https://paste.yunohost.org/raw/emipowuvik

**Comment by syrabo** [comment]
This is also the case for me: https://paste.yunohost.org/raw/lorahisozi

**Comment by yalh76** [comment]
The error is :
```
LoadError: Could not open library '/var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/blurhash-0.1.6/lib/../ext/blurhash/encode.so': /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/blurhash-0.1.6/lib/../ext/blurhash/encode.so: cannot open shared object file: No such file or directory
```
Should be related to  https://github.com/Gargron/blurhash/issues/22 already fixed by https://github.com/Gargron/blurhash/pull/20 and will be fixed with a new release of https://github.com/Gargron/blurhash/tags actually at 0.1.6

**Comment by badrihippo** [comment]
I got this to work for Hometown by patching `Gemfile` and `Gemfile.lock` to use the (fixed) GitHub versions of `blurhash` and `ox`. (I was trying to fork this repo to install [Hometown](https://github.com/hometown-fork/hometown/) instead of Mastodon, hence the testing with Hometown!)

I'll test it once with Mastodon proper and then create a PR, but till then here's the patch:

```
diff --git a/Gemfile b/Gemfile
index 7c36bc6b8..3f691d102 100644
--- a/Gemfile
+++ b/Gemfile
@@ -22,7 +22,8 @@
 gem 'fog-core', '<= 2.1.0'
 gem 'fog-openstack', '~> 0.3', require: false
 gem 'kt-paperclip', '~> 7.1'
-gem 'blurhash', '~> 0.1'
+gem 'blurhash', github: 'Gargron/blurhash', ref: '870a34e01ce7d09a7bd4d700435e1764ca823246'
+
 
 gem 'active_model_serializers', '~> 0.10'
 gem 'addressable', '~> 2.8'

diff --git a/Gemfile.lock b/Gemfile.lock
index 7c36bc6b8..3f691d102 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -7,6 +7,13 @@
       hkdf (~> 0.2)
       jwt (~> 2.0)
 
+GIT
+  remote: https://github.com/Gargron/blurhash.git
+  revision: 870a34e01ce7d09a7bd4d700435e1764ca823246
+  ref: 870a34e01ce7d09a7bd4d700435e1764ca823246
+  specs:
+    blurhash (0.1.6)
+
 GEM
   remote: https://rubygems.org/
   specs:
@@ -120,8 +127,6 @@
     bindata (2.4.10)
     binding_of_caller (1.0.0)
       debug_inspector (>= 0.0.1)
-    blurhash (0.1.6)
-      ffi (~> 1.14)
     bootsnap (1.13.0)
       msgpack (~> 1.2)
     brakeman (5.3.1)
@@ -448,7 +453,7 @@
     openssl-signature_algorithm (1.2.1)
       openssl (> 2.0, < 3.1)
     orm_adapter (0.5.0)
-    ox (2.14.11)
+    ox (2.14.13)
     parallel (1.22.1)
     parser (3.1.2.1)
       ast (~> 2.4.1)
@@ -738,7 +743,7 @@
   aws-sdk-s3 (~> 1.114)
   better_errors (~> 2.9)
   binding_of_caller (~> 1.0)
-  blurhash (~> 0.1)
+  blurhash!
   bootsnap (~> 1.13.0)
   brakeman (~> 5.3)
   browser
```

Save that as `sources/patches/app-blurhash-bugfix.patch` under the repo folder and then the install should (hopefully) work.
