### ISSUE TITLE
Mastodon will no longer install following update

### ISSUE THREAD

**Issue by lordforbes** [YunoHost-Apps/mastodon_ynh#358]
Following a fresh install of Yunonost ISO on an on-prem HP Server (32gb RAM 8tb drive) I get the same issue installing Mastodon as the other people who have posted over the last few days,

I have pasted the log but it's the same content. The specific error appears to be

LoadError: Could not open library '/var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/blurhash-0.1.6/lib/../ext/blurhash/encode.so': /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/blurhash-0.1.6/lib/../ext/blurhash/encode.so: cannot open shared object file: No such file or directory

[mastodon.txt](https://github.com/YunoHost-Apps/mastodon_ynh/files/10329571/mastodon.txt)

**Comment by badrihippo** [comment]
Looks like the same issue as #356. Linking the log from that report here because it's on YunoPaste an can be opened without downloading: https://paste.yunohost.org/raw/jojejugumu

**Comment by yalh76** [comment]
not an upgrade issue but a mastodon install issue, follow at #357
