### ISSUE TITLE
Erreur suite à montée de version installation from SCRATCH 4.0.2~ynh2

### ISSUE THREAD

**Issue by franckhomer** [YunoHost-Apps/mastodon_ynh#369]
SERVEUR OVH
DEBIAN 9 STRETCH (64bits)
yunohost_version: 11.1.10
accès SSH et web

    Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no
Bonjour tout le monde,
Suite à un plantage lors de la montée de version en 4.0.2~ynh2 j'ai eu un gros plantage.
Impossible de reprendre le backup.
J'ai tout réinstallé de 0 mais je voudrais remettre la BD de la sauvegarde
Comment puis-je l'importer?
Est-ce que je peux uniquement importer certaines tables liés aux utilisateurs et à leurs messages?

merci de votre aide

**Comment by Tagadda** [comment]
Bonjour, est-ce que c'est toujours d'actualité ?
Pour ce genre de problème je pense que tu auras plus de réponse sur le forum
