### ISSUE TITLE
Update to 4.1.0

### ISSUE THREAD

**Issue by PraetorIM** [YunoHost-Apps/mastodon_ynh#374]
Mastodon released version 4.1.0 about 3 weeks ago. Is it foreseeable when this update can also be installed with Yunohost?

**Comment by jcrabapple** [comment]
I'm wondering the same thing. I may just upgrade using the standard Mastodon upgrade method.

**Comment by panomaki** [comment]
You may want to check #367.

**Comment by PraetorIM** [comment]
Another 3 weeks. Any new information?

**Comment by panomaki** [comment]
See https://github.com/YunoHost-Apps/mastodon_ynh/pull/378.

**Comment by yalh76** [comment]
already at 4.1.2~ynh1
