### ISSUE TITLE
how to migrate existing instance database to fresh install?

### ISSUE THREAD

**Issue by SmallPatatas** [YunoHost-Apps/mastodon_ynh#384]
### Describe the bug

Trying to figure out if there is a way to migrate an instance on YunoHost using the method described here, where the essential files are transferred to a new Mastodon install (but without the Mastodon:setup step):
https://docs.joinmastodon.org/admin/migrating/

### Context

- Hardware: Raspberry Pi at home
- YunoHost version: 11.1.20, Mastodon 4.1.2~ynh
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?:yes
  - If yes, please explain:

I had changed the character limit as described here https://www.draklyckan.se/2021/11/how-to-increase-the-character-limit-for-toots-in-mastodon/ but was getting a notification at the `RAILS_ENV=production bundle exec rails assets:precompile` step that (to the best of my recollection) said I should upgrade npm.

So, naively, I did that. Now I'm in what I think people call "dependency hell" where the Mastodon homepage is a blank screen on everyone else's computer/phone but my own, and compiling fails with things like "update postcss to version 8" even though it seems to already be there. 

I'm really out of my depth as a noob here :/

So I'm hoping that I can find a way to reinstall YunoHost/Mastodon in such a way that I can migrate the database, secrets, etc rather than do a 'backup/restore' in the standard YunoHost way for installs that haven't been broken by a silly noob admin

Thanks :)

**Comment by Tagadda** [comment]
I think you could try to restore the backup and then force an app upgrade with `sudo yunohost app upgrade mastodon -F`.
