### ISSUE TITLE
Upgrade from 4.0.2 to 4.1.2 fails

### ISSUE THREAD

**Issue by BishopGreer** [YunoHost-Apps/mastodon_ynh#386]
### Describe the bug

Upgrade of Mastodon causes error and fails. 

### Context

- Hardware: *VPS bought online 
- YunoHost version: 11.1.21.4
- I have access to my server: *Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no 
  - If yes, please explain:
- Using, or trying to install package version/branch: 4.1.2
- If upgrading, current package version: 4.0.2

### Steps to reproduce

-Go to upgrade 
Click upgrade for Mastodon
Upgrade fails

### Logs
Log (https://paste.yunohost.org/raw/gikunoniqi)

![IMG_1036](https://github.com/YunoHost-Apps/mastodon_ynh/assets/121546259/8d135d46-8ef5-406b-a361-fddc142a6478)

**Comment by Tagadda** [comment]
The upgrade fails because the backup fails.
`2023-06-30 15:18:08,589: WARNING - 774  A backup archive with this name already exists.`
You can delete the backup named `mastodon-pre-upgrade2` and try again.

**Comment by BishopGreer** [comment]
When I go to the backup page, I get a blank page with no backups listed.
