### ISSUE TITLE
Token error with private app nginx setting

### ISSUE THREAD

**Issue by nemsia** [YunoHost-Apps/mastodon_ynh#4]
When the private app setting is on, set by default.
I have many token error on login or when i trying to fallow users on anothers instances.

**Comment by magikcypress** [comment]
I think that's okay, I'll find out. I just changed the status of the application to the installation for public.

**Comment by nemsia** [comment]
Thanks ;)

**Comment by nemsia** [comment]
I reopen because the app is private by default.
I test on my repo to re-add:
ynh_app_setting_set "$app" unprotected_uris "/"

**Comment by magikcypress** [comment]
See #5
