### ISSUE TITLE
Install crash when password has simple quote

### ISSUE THREAD

**Issue by tibs245** [YunoHost-Apps/mastodon_ynh#41]
Hi,

I had a problem with dependencies :

```
Installation failed
[0m
+ echo -e '\e[0m'
+ sudo systemctl reload nginx
+ sudo userdel -f mastodon
+ echo '/usr/bin/ruby doesn'\''t deleted because it'\''s not exist.'
+ '[' -e /usr/bin/ruby ']'
+ [[ y = \/ ]]
+ [[ /usr/bin/ruby =~ ^/[[:alnum:]]+$ ]]
+ [[ /var/www /home/yunohost.app =~ /usr/bin/ruby ]]
+ forbidden_path=' /var/www /home/yunohost.app'
+ path_to_remove=/usr/bin/ruby
/usr/bin/ruby doesn't deleted because it's not exist.
+ ynh_secure_remove /usr/bin/ruby
+ sudo rm -R /etc/apt/sources.list.d/yarn.list
+ '[' -e /etc/apt/sources.list.d/yarn.list ']'
+ [[ t = \/ ]]
+ [[ /etc/apt/sources.list.d/yarn.list =~ ^/[[:alnum:]]+$ ]]
+ [[ /var/www /home/yunohost.app =~ /etc/apt/sources\.list\.d/yarn\.list ]]
+ forbidden_path=' /var/www /home/yunohost.app'
+ path_to_remove=/etc/apt/sources.list.d/yarn.list
+ ynh_secure_remove /etc/apt/sources.list.d/yarn.list
+ sudo rm -R /etc/apt/sources.list.d/backports.list
+ '[' -e /etc/apt/sources.list.d/backports.list ']'
```

so **/usr/bin/ruby doesn't deleted because it's not exist.** And my yunohost work correctly.

Ruby is not specified as a dependency ?

**Comment by nemsia** [comment]
Your installation as fail and yunohost run the remove script.
Ruby is installed by rbenv:
```
# Install ruby-build
sudo su - $app <<RCOMMANDS
/opt/mastodon/.rbenv/bin/rbenv install 2.4.1
/opt/mastodon/.rbenv/versions/2.4.1/bin/ruby -v
RCOMMANDS

# Create symlink for ruby
sudo ln -s /opt/mastodon/.rbenv/versions/2.4.1/bin/ruby /usr/bin/ruby || true 
```
Have you the completed install log to find your problem?

**Comment by tibs245** [comment]
Oh ! I just saw, My password have simple quote. And your script has not like it ^^'

I try without simple quote during installation

**Comment by tibs245** [comment]
My log is too big for in comment, I can send it to your email address if you want :)

**Comment by tibs245** [comment]
It's ok when I use a password without simple quote :) 

We just need adapt the installation script to not crash when password has simple quote I think..

If I have the time tomorrow, maybe I will fix them :)

**Comment by Jibec** [comment]
@nemsia: here is how I do to prevent this kind of issue: https://github.com/Jibec/peertube_ynh/commit/22da9d4b4ccbb45d8b1684211b0f9f964e160392

Remember you'll have to add `mailutils` to your dependencies, because Raspbian doesn't include it by default. YNH Dev team wrote a commit to add it to YunoHost defaults, but it's not released yet.

**Comment by nemsia** [comment]
Fixed by https://github.com/YunoHost-Apps/mastodon_ynh/pull/100
