### ISSUE TITLE
4.2.0 upgrade failure 

### ISSUE THREAD

**Issue by yelvington** [YunoHost-Apps/mastodon_ynh#412]
Warnings.

### Context

- Hardware: Raspberry Pi at home 
- YunoHost version: 11.2.4
- I have access to my server: Through SSH
- Using, or trying to install package version/branch: 4.2.0 
- If upgrading, current package version: 4.1.9

Not sure if this is significant, but I noticed it while upgrading, so here it is. 
[...]

**Comment by yelvington** [comment]
Well, crap.

10282410 DEBUG info There appears to be trouble with your network connection. Retrying...
10316146 DEBUG info There appears to be trouble with your network connection. Retrying...
10357116 DEBUG info There appears to be trouble with your network connection. Retrying...
10390460 DEBUG info There appears to be trouble with your network connection. Retrying...
10428437 WARNING error An unexpected error occurred: "https://registry.yarnpkg.com/@material-design-icons/svg/-/svg-0.14.12.tgz: ESOCKETTIMEDOUT".
10428438 DEBUG info If you think this is a bug, please open a bug report with the information provided in "/var/www/mastodon/live/yarn-error.log".
10428439 DEBUG info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
10468748 DEBUG + ynh_exit_properly
10469408 DEBUG + local exit_code=1
10469409 DEBUG + [[ upgrade =~ ^install$|^upgrade$|^restore$ ]]
10469411 DEBUG + rm -rf /var/cache/yunohost/download/
10471776 DEBUG + '[' 1 -eq 0 ']'
10471777 DEBUG + trap '' EXIT
10471778 DEBUG + set +o errexit
10471779 DEBUG + set +o nounset
10471779 DEBUG + sleep 0.5
10472280 DEBUG + type -t ynh_clean_setup
10472282 DEBUG + ynh_clean_setup
10472283 DEBUG + ynh_restore_upgradebackup
10472284 DEBUG + ynh_print_err '--message=Upgrade failed.'
10472284 DEBUG + local legacy_args=m
10472285 DEBUG + args_array=(['m']='message=')
10472285 DEBUG + local -A args_array
10472286 DEBUG + local message
10472286 DEBUG + ynh_handle_getopts_args '--message=Upgrade failed.'
10472287 DEBUG + set +o xtrace
10472321 WARNING [Error] Upgrade failed.
10472324 DEBUG + ynh_print_log '[Error] Upgrade failed.'
10472325 DEBUG + echo -e '[Error] Upgrade failed.'
10472325 DEBUG + local app_bck=mastodon
10472326 DEBUG + NO_BACKUP_UPGRADE=0
10472327 DEBUG + '[' 0 -eq 0 ']'
10472328 DEBUG + ynh_backup_archive_exists mastodon-pre-upgrade2
10472328 DEBUG + yunohost backup list --output-as json --quiet
10472329 DEBUG + jq -e --arg archive mastodon-pre-upgrade2 '.archives | index($archive)'
10517693 DEBUG + yunohost app remove mastodon
10518651 DEBUG Removing mastodon...
10519349 DEBUG [+...................] > Loading installation settings...
10521527 DEBUG [#++.................] > Removing mastodon-web service integration...
10523495 DEBUG [###++...............] > Removing mastodon-sidekiq service integration...
10525439 DEBUG [#####+..............] > Removing mastodon-streaming service integration...
10526489 DEBUG [######++............] > Stopping and removing the systemd service...
10531632 DEBUG [########++..........] > Removing the PostgreSQL database...
10535938 DEBUG [##########+.........] > Removing app main directory...

**Comment by yelvington** [comment]
Yuck. Any advice on how to make use of that painfully constructed, huge backup tarfile?

**Comment by Tagadda** [comment]
Please use YunoPaste to share logs.

**Comment by mossymossmoss** [comment]
The upgrade failed for me as well. Here is my log:
https://paste.yunohost.org/raw/hanoxerufu

**Comment by panomaki** [comment]
> The upgrade failed for me as well. Here is my log: https://paste.yunohost.org/raw/hanoxerufu

It seems you ran out of disk space halfway:
`2023-09-25 19:41:57,793: WARNING - error Could not write file "/var/www/mastodon/live/yarn-error.log": "ENOSPC: no space left on device, write"`

**Comment by mossymossmoss** [comment]
Ah, that could be it. It seems the backup was 12gb, which seems rather large. Does Yunohost back up all the cached media from other instances?

**Comment by Tagadda** [comment]
Yes, if we don't backup cached media then it would causes issues within mastodon. And we can filter out subfolders in yunohost backups, yet.
You probably want to run `tootctl media remove` before running the upgrade.

**Comment by yelvington** [comment]
Mine is about 36 gigabytes, and it's still running, apparently trying to restore 4.1.9. 

https://paste.yunohost.org/raw/epoxocetut

**Comment by yelvington** [comment]
Failure finally completed. Takes a long time on a Raspberry Pi. 

https://paste.yunohost.org/raw/qureviseyu
