### ISSUE TITLE
401 Le jeton d'accès n'est pas valide

### ISSUE THREAD

**Issue by Rafi594** [YunoHost-Apps/mastodon_ynh#43]
Bonjour

J'ai un problème avec mon instance

Depuis ce matin j'ai cette erreur qui apparait 

401 Le jeton d'accès n'est pas valide

Merci d'avance pour vos réponses

**Comment by nemsia** [comment]
Bonjour,
Ce problème arrive rarement mais tu peut le régler en supprimant les cookies relatifs à ton instance dans ton navigateur .

**Comment by Rafi594** [comment]
Mon problème est revenu et supprimer les cookies ne fait rien

401Le jeton d'accès n'est pas valide

**Comment by tibs245** [comment]
Salut,
Tu supprime correctement notament les cookies du domains principal ?
