### ISSUE TITLE
La migration vers 1.4.2/1.4.3 ne passe pas

### ISSUE THREAD

**Issue by MCMic** [YunoHost-Apps/mastodon_ynh#44]
https://github.com/tootsuite/mastodon/releases/tag/v1.4.2
Visiblement ya une étape de migration supplémentaire pour préparer la BDD à l’ajout des contraintes, elle doit manquer dans le script upgrade car ça échoue en se plaignant de contraintes pas respectées dans les données existantes.

**Comment by nemsia** [comment]
C'est parfait, j’attends juste la fin du test pour validé le PR
