### ISSUE TITLE
Critical security update available! v4.2.7

### ISSUE THREAD

**Issue by GeekAnnoyed** [YunoHost-Apps/mastodon_ynh#444]
### Describe the bug

I'm getting a warning that there has been a bug fix via a web UI notification and direct message from update_notifications@mastodon.online 
with a link to https://github.com/mastodon/mastodon/releases/tag/v4.2.7

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.2.10
- I have access to my server: *Through SSH &  through the webadmin.*
-
### Steps to reproduce

Access the public web interface
top left is a message
"Critical security update available!

Please update your Mastodon server as soon as possible! [See updates]

I'm not familiar enough with the code yet to commit a PR
sorry if this was the wrong place to do this

**Comment by Tagadda** [comment]
Hey,
#443 just got merged.
