### ISSUE TITLE
where is 4.2.7?

### ISSUE THREAD

**Issue by dhuschde** [YunoHost-Apps/mastodon_ynh#446]
This GitHub says Mastodon is already on 4.2.7. But neither my Server nor the [App Catalog](https://apps.yunohost.org/app/mastodon) show the new Version, they are still on 4.2.6.

**Comment by adrienlacombe-ledger** [comment]
+1

**Comment by panomaki** [comment]
I had the same problem yesterday; I presume this is something to do with the yunohost tools infrastructure?

The following works to apply this critical update, if you have command line access to your server:

```
$ sudo apt-get install screen
$ screen
$ sudo yunohost app upgrade mastodon -u https://github.com/YunoHost-Apps/mastodon_ynh --debug 
```

(You may want to clear your cache and/or skip the backup with -b to speed things up)
