### ISSUE TITLE
security update  4.2.10

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/mastodon_ynh#453]
Hello, 

in case you missed it:

https://github.com/mastodon/mastodon/security/advisories/GHSA-xjvf-fm67-4qc3
https://github.com/mastodon/mastodon/security/advisories/GHSA-58x8-3qxw-6hm7
https://github.com/mastodon/mastodon/security/advisories/GHSA-c2r5-cfqr-c553
https://github.com/mastodon/mastodon/security/advisories/GHSA-q3rg-xx5v-4mxh
https://github.com/mastodon/mastodon/security/advisories/GHSA-vp5r-5pgw-jwqx
https://github.com/mastodon/mastodon/security/advisories/GHSA-5fq7-3p3j-9vrf

patched  with v 4.2.10  https://github.com/mastodon/mastodon/releases/tag/v4.2.10

thx for your work ;)

isAAAc

**Comment by stilobique** [comment]
On the way with the #452 PR.
