### ISSUE TITLE
Update Ruby to 3.2.3

### ISSUE THREAD

**Issue by nizarus** [YunoHost-Apps/mastodon_ynh#455]
### Describe the bug

The Yunohost mastodon app is still using Ruby 3.2.2, but tootcl command needs 3.2.3 version. As workaround, we install Ruby 3.2.3 manually but after each upgrade the 3.2.3 version is removed and 3.2.2 version is installed.

### Context

- Hardware: VPS bought online
- YunoHost version: 11.2.20.2
- I have access to my server: Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: Ruby 3.2.3 installed manually
- Using, or trying to install package version/branch:
- If upgrading, current package version: mastodon 4.2.10~ynh1

### Steps to reproduce

```
$ sudo yunohost app upgrade mastodon -u https://github.com/YunoHost-Apps/mastodon_ynh --debug
...
INFO Removing Ruby-3.2.3
INFO Installing Ruby 3.2.2
...
# RAILS_ENV=production bin/tootctl media usage
rbenv: version `3.2.3' is not installed (set by /var/www/mastodon/live/.ruby-version)
```

### Expected behavior

Getting tootcl working.

**Comment by nschiwy** [comment]
While we're waiting for this to get merged, I wanted to see if you all could give me any advice on how to upgrade ruby manually on my setup. Whenever I try to run commands as the Mastodon user it tells me that rbenv is not found. I tried running some commands as root but I'm worried I just made things worse. My server just ballooned out of control without the pruning commands and I had to shut down all of the mastodon services until I can get Ruby working again.

**Comment by elacheche** [comment]
> While we're waiting for this to get merged, I wanted to see if you all could give me any advice on how to upgrade ruby manually on my setup. Whenever I try to run commands as the Mastodon user it tells me that rbenv is not found. I tried running some commands as root but I'm worried I just made things worse. My server just ballooned out of control without the pruning commands and I had to shut down all of the mastodon services until I can get Ruby working again.

Hello,

Sorry for the delayed answer, here is how I do it, as `root` user:

```bash
source /etc/profile.d/rbenv.sh
RUBY_CONFIGURE_OPTS=--with-jemalloc rbenv install 3.2.3
```

Then `tootctl` should be good.

**Comment by nschiwy** [comment]
Thank you so much for posting this. For some reason my system is still spitting out errors so I'm gonna make a post in the yunohost forums to see if they can help me figure out what's going on.

**Comment by bigjdunham** [comment]
I'm still having trouble with this even after the latest upgrade. The workaround suggested by @elacheche did not work for me. I'm getting a "/usr/bin/env: ‘ruby’: No such file or directory" when I try to use tootctl.

**Comment by Tagadda** [comment]
To use `tootctl`, you can use this:
```
# cd /var/www/mastodon/live
# sudo -u mastodon RAILS_ENV=production PATH=/opt/rbenv/versions/mastodon/bin bin/tootctl --help
```

**Comment by nizarus** [comment]
@bigjdunham which version you have ?
I confirm that with 4.2.12~ynh1 version, tootcl is working from scratch.
