### ISSUE TITLE
Can't go to Administration settings

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/mastodon_ynh#459]
### Describe the bug

After login as the administrator, if I try to go to the /admin/dashboard page, it doesn't. It remains on /auth/edit page.
It says

> Your request is pending review by our staff. This may take some time. You will receive an e-mail if your request is approved.

### Expected behavior

Be able to manage my mastodon instance going to administration settings.

**Comment by Thatoo** [comment]
I can't go to any other page than this one

![image](https://github.com/user-attachments/assets/1bf10a6c-403a-4bae-9eb2-89f55f65e2cd)

**Comment by dr41nU** [comment]
Hello,
Seems to be an upstream bug for this version : https://github.com/mastodon/mastodon/issues/29380
So according to https://github.com/YunoHost-Apps/mastodon_ynh/blob/master/doc/ADMIN.md, the complete command should be:
`sudo -u mastodon RAILS_ENV=production PATH=/opt/rbenv/versions/mastodon/bin ./bin/tootctl account modify USER --approve` (in `/var/www/mastodon/live`, as root)

**Comment by Thatoo** [comment]
Thank you. Indeed, it works!
