### ISSUE TITLE
MAJ 1.5.0 fail

### ISSUE THREAD

**Issue by vincentux** [YunoHost-Apps/mastodon_ynh#47]
J'ai lancé la MAJ pour passer en 1.5.0, tout c'est très bien passé, pas de message d'erreur.
Mais je suis toujours en 1.4.7 ... :'(
Faut-il attendre une modif au niveau de l'apps ?

**Comment by nemsia** [comment]
Bonjour,
Merci de le signaler, les ajouts de dépendance pour la 1.5 sont prêtes, je les mets tout de suite.

**Comment by nemsia** [comment]
Pardon, j'ai regardé un peu trop vite, c'est une version Release Candidate qui vient de sortir et l'appli yunohost n'installe que la version Latest "Stable".

**Comment by vincentux** [comment]
ah ok, merci.

**Comment by nemsia** [comment]
Si veut la tester tu peut utiliser ma branch de dev:
https://github.com/nemsia/mastodon_ynh/tree/upgrade-from-pre-release

**Comment by vincentux** [comment]
c'est sympa mais je vais attendre, je suis pas à la minute ;)
