### ISSUE TITLE
401 access token is invalid

### ISSUE THREAD

**Issue by xpd259** [YunoHost-Apps/mastodon_ynh#5]
Hello, 
I thought I'd give this a whirl on my spare box and it seems to install fine
but I'm getting a "401 access token is invalid" error

I'm not sure what logs to attach.
but if you require anything please let me know 👍 

![screenshot_20170419_154332](https://cloud.githubusercontent.com/assets/822758/25186079/f9a8325c-2516-11e7-84d2-63ad4ede7177.png)

**Comment by magikcypress** [comment]
Yes, sorry for that ! It's a bug !

For the moment, comment this line `access_by_lua_file /usr/share/ssowat/access.lua;` into la nginx domain config file `/etc/nginx/conf.d/mydomain.conf`

**Comment by xpd259** [comment]
Phew, you have no idea how anxious I was that it was just me 
I'm always worried about reporting bugs.

but thanks for the swift reply and fix 👍

**Comment by magikcypress** [comment]
All mastodon services are up ?

`sudo systemctl status mastodon-web.service mastodon-sidekiq.service mastodon-streaming.service`

**Comment by xpd259** [comment]
yes, to make sure I restarted the entire server
I removed rather than commenting the line and I've not got a mastodon
"we're sorry, but something went wrong"
but no details on the browser


root@epoc:/home/dthomas# systemctl status mastodon-web.service
mastodon-sidekiq.service mastodon-streaming.service
● mastodon-web.service -
mastodon-web

   Loaded: loaded (/etc/systemd/system/mastodon-web.service; enabled)
   Active: active (running) since Wed 2017-04-19 18:15:00 BST; 20min ago
 Main PID: 488 (bundle)
   CGroup: /system.slice/mastodon-web.service
           ├─ 488 puma 3.8.2 (tcp://0.0.0.0:3000) [live]
           ├─2012 puma: cluster worker 0: 488 [live]
           └─2016 puma: cluster worker 1: 488 [live]

Apr 19 18:25:54 epoc bundle[488]: Is the server running locally and
accepting
Apr 19 18:25:54 epoc bundle[488]: connections on Unix domain socket
"/var/run/postgresql/.s.PGSQL.5432"?
Apr 19 18:25:54 epoc bundle[488]: ' duration=2.26 view=0.00
Apr 19 18:25:54 epoc bundle[488]: [6e269552-d1e1-4b0c-a7a4-f91d4472c747]
Apr 19 18:25:54 epoc bundle[488]: [6e269552-d1e1-4b0c-a7a4-f91d4472c747]
PG::ConnectionBad (could not connect to server: No such file or directory
Apr 19 18:25:54 epoc bundle[488]: Is the server running locally and
accepting
Apr 19 18:25:54 epoc bundle[488]: connections on Unix domain socket
"/var/run/postgresql/.s.PGSQL.5432"?
Apr 19 18:25:54 epoc bundle[488]: ):
Apr 19 18:25:54 epoc bundle[488]: [6e269552-d1e1-4b0c-a7a4-f91d4472c747]
Apr 19 18:25:54 epoc bundle[488]: [6e269552-d1e1-4b0c-a7a4-f91d4472c747]
app/controllers/concerns/localized.rb:15:in `set_locale'

● mastodon-sidekiq.service - mastodon-sidekiq
   Loaded: loaded (/etc/systemd/system/mastodon-sidekiq.service; enabled)
   Active: active (running) since Wed 2017-04-19 18:15:00 BST; 20min ago
 Main PID: 486 (bundle)
   CGroup: /system.slice/mastodon-sidekiq.service
           └─486 sidekiq 4.2.10 live [0 of 20 busy]

Apr 19 18:15:00 epoc systemd[1]: Started mastodon-sidekiq.
Apr 19 18:17:02 epoc bundle[486]: 2017-04-19T17:17:02.915Z 486
TID-ot4z7353k INFO: Booting Sidekiq 4.2.10 with redis options
{:host=>"127.0.0.1", :port=>"6379", :db=>0, :password=>false, :url=>nil}
Apr 19 18:17:12 epoc bundle[486]: Creating scope :cache_ids. Overwriting
existing method Notification.cache_ids.
Apr 19 18:17:13 epoc bundle[486]: 2017-04-19T17:17:13.625Z 486
TID-ot4z7353k INFO: Running in ruby 2.4.1p111 (2017-03-22 revision 58053)
[x86_64-linux]
Apr 19 18:17:13 epoc bundle[486]: 2017-04-19T17:17:13.626Z 486
TID-ot4z7353k INFO: See LICENSE and the LGPL-3.0 for licensing details.
Apr 19 18:17:13 epoc bundle[486]: 2017-04-19T17:17:13.626Z 486
TID-ot4z7353k INFO: Upgrade to Sidekiq Pro for more features and support:
http://sidekiq.org
Apr 19 18:17:13 epoc bundle[486]: 2017-04-19T17:17:13.634Z 486
TID-ot4z7353k INFO: Starting processing, hit Ctrl-C to stop

● mastodon-streaming.service - mastodon-streaming
   Loaded: loaded (/etc/systemd/system/mastodon-streaming.service; enabled)
   Active: active (running) since Wed 2017-04-19 18:15:00 BST; 20min ago
 Main PID: 489 (npm)
   CGroup: /system.slice/mastodon-streaming.service
           ├─ 489 npm
           ├─1578 sh -c babel-node ./streaming/index.js --presets
es2015,stage-2
           ├─1579 node /opt/mastodon/live/node_modules/.bin/babel-node
./streaming/index.js --presets es2015,stage-2
           ├─1607 /usr/bin/nodejs
/opt/mastodon/live/node_modules/babel-cli/lib/_babel-node
./streaming/index.js --presets es2015,stage-2
           └─1872 /usr/bin/nodejs
/opt/mastodon/live/node_modules/babel-cli/lib/_babel-node.js
/opt/mastodon/live/streaming/index.js --presets es2015,stage-2

Apr 19 18:15:00 epoc systemd[1]: Started mastodon-streaming.
Apr 19 18:15:50 epoc npm[489]: > mastodon@ start /opt/mastodon/live
Apr 19 18:15:50 epoc npm[489]: > babel-node ./streaming/index.js --presets
es2015,stage-2
Apr 19 18:16:48 epoc npm[489]: info Starting streaming API server master
with 1 workers
Apr 19 18:16:50 epoc npm[489]: info Starting streaming API server worker on
port 4000



regards
Dick Thomas


Forums and Mailing List: "You will never find a more wretched hive of scum
and villainy. We must be cautious."‌‌

**Comment by xpd259** [comment]
the nginx log is as follows
```
root@epoc:/home/dthomas# tailf /var/log/nginx/social.speaksthegeek.co.uk-error.log 
2017/04/19 18:11:15 [error] 729#0: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 81.174.251.227, server: social.speaksthegeek.co.uk, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "social.speaksthegeek.co.uk", referrer: "https://speaksthegeek.co.uk/yunohost/sso/?r=aHR0cHM6Ly9zb2NpYWwuc3BlYWtzdGhlZ2Vlay5jby51ay8="
2017/04/19 18:12:26 [error] 2306#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 81.174.251.227, server: social.speaksthegeek.co.uk, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "social.speaksthegeek.co.uk"
2017/04/19 18:12:27 [error] 2306#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 81.174.251.227, server: social.speaksthegeek.co.uk, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "social.speaksthegeek.co.uk"
2017/04/19 18:16:04 [error] 713#0: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 81.174.251.227, server: social.speaksthegeek.co.uk, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "social.speaksthegeek.co.uk", referrer: "https://speaksthegeek.co.uk/yunohost/sso/?r=aHR0cHM6Ly9zb2NpYWwuc3BlYWtzdGhlZ2Vlay5jby51ay8="
2017/04/19 18:16:07 [error] 713#0: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 81.174.251.227, server: social.speaksthegeek.co.uk, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "social.speaksthegeek.co.uk", referrer: "https://speaksthegeek.co.uk/yunohost/sso/?r=aHR0cHM6Ly9zb2NpYWwuc3BlYWtzdGhlZ2Vlay5jby51ay8="
2017/04/19 18:16:09 [error] 713#0: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 81.174.251.227, server: social.speaksthegeek.co.uk, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "social.speaksthegeek.co.uk", referrer: "https://speaksthegeek.co.uk/yunohost/sso/?r=aHR0cHM6Ly9zb2NpYWwuc3BlYWtzdGhlZ2Vlay5jby51ay8="
2017/04/19 18:16:10 [error] 713#0: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 81.174.251.227, server: social.speaksthegeek.co.uk, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "social.speaksthegeek.co.uk", referrer: "https://speaksthegeek.co.uk/yunohost/sso/?r=aHR0cHM6Ly9zb2NpYWwuc3BlYWtzdGhlZ2Vlay5jby51ay8="
2017/04/19 18:16:51 [error] 713#0: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 81.174.251.227, server: social.speaksthegeek.co.uk, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "social.speaksthegeek.co.uk", referrer: "https://speaksthegeek.co.uk/yunohost/sso/?r=aHR0cHM6Ly9zb2NpYWwuc3BlYWtzdGhlZ2Vlay5jby51ay8="
2017/04/19 18:16:53 [error] 713#0: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 81.174.251.227, server: social.speaksthegeek.co.uk, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "social.speaksthegeek.co.uk", referrer: "https://speaksthegeek.co.uk/yunohost/sso/?r=aHR0cHM6Ly9zb2NpYWwuc3BlYWtzdGhlZ2Vlay5jby51ay8="
2017/04/19 18:16:55 [error] 713#0: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 81.174.251.227, server: social.speaksthegeek.co.uk, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "social.speaksthegeek.co.uk", referrer: "https://speaksthegeek.co.uk/yunohost/sso/?r=aHR0cHM6Ly9zb2NpYWwuc3BlYWtzdGhlZ2Vlay5jby51ay8="
```

**Comment by magikcypress** [comment]
Into mastodon web service, i read this message.
> PG::ConnectionBad (could not connect to server: No such file or directory

Postgresql connexion is down.

You have information into config file /opt/mastodon/.env.production (section postgresql) ?

**Comment by xpd259** [comment]
just the defaults
```# Service dependencies
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
# REDIS_DB=0
DB_HOST=/var/run/postgresql
DB_USER=mastodon
DB_NAME=mastodon_production
DB_PASS=
DB_PORT=5432
```
 the only thing I've changed in this file is my email settings

**Comment by xpd259** [comment]
okay, sorry for the extra confusion
the DB was damaged. all sorted now

**Comment by nemsia** [comment]
I can reproduce the bug, yunohost make this app in private by default.

**Comment by magikcypress** [comment]
Can you explain how you fixed the problem for other users who may have the same problem?

Thanks

**Comment by nemsia** [comment]
For fast fix (and dirty) you can comment two line (one for http and one for https):
access_by_lua_file /usr/share/ssowat/access.lua;
in /etc/nginx/conf.d/domain.tld.conf

**Comment by nemsia** [comment]
For better fix and for new install:
[Last commit](https://github.com/nemsia/mastodon_ynh/commit/bcf1d5d3d4d763caa091309c7dee10d442a89141)

**Comment by magikcypress** [comment]
Thanks, can you create a PR guys ?

**Comment by vincentux** [comment]
Une fois la PR créée, 
une simple MAJ suffira ou faudra-t-il ré-installer Mastodon ?

**Comment by nemsia** [comment]
Pour l'instan celà n'est valable que pour une nouvelle installation.
Je vais tester s'il est possible de l’intégrée dans l'upgrade.

**Comment by magikcypress** [comment]
@nemsia Add a comment in your repo and add PR for this problem.

Thanks

**Comment by vincentux** [comment]
Du coup c'est fixé ou pas encore ?

**Comment by magikcypress** [comment]
Yep, normalement c'est bon pour l'erreur 401 demande de token.

**Comment by nemsia** [comment]
Ça fonctionne pour moi.Le 20 avr. 2017 7:07 PM, __cyp <notifications@github.com> a écrit :Yep, normalement c'est bon pour l'erreur 401 demande de token.

**Comment by nemsia** [comment]
Try with private session or another internet browser if you have this token error.

**Comment by arthurlutz** [comment]
I seem to be getting this bug on a recent install of yunohost, looking at https://github.com/YunoHost-Apps/mastodon_ynh/pull/7 it was closed and not merged, any pointers to where the PR that fixed this is ? (thanks in advance!)

**Comment by nemsia** [comment]
This error only need to clean browser cookies and cache. Or try with another browser.

**Comment by autra** [comment]
I still reproduce that after cleaning browser cookie and cache with firefox only (chromium ok). Fresh installation of yunohost and mastodon.

**Comment by hieronymousch** [comment]
Fresh install, first app to test and have this issue as well.

**Comment by yalh76** [comment]
issue referenced at https://github.com/YunoHost-Apps/mastodon_ynh/issues/6

**Comment by danger89** [comment]
I got this issue on my own Mastodon instance. I'm running behind Nginx.
![image](https://user-images.githubusercontent.com/628926/203841339-dd3879df-f2ba-4800-9f35-437aeca2a95f.png)

See also: https://github.com/mastodon/mastodon/issues/1490#issuecomment-1326718615

What was your solution fix this isssue?
