### ISSUE TITLE
Erreur vers la mise à jour 1.5 raspberry pi

### ISSUE THREAD

**Issue by Rafi594** [YunoHost-Apps/mastodon_ynh#50]
Bonjour,

J'ai essayé de mettre à jour mon mastodon en version 1.5 mais ces erreur apparaissent
https://paste.yunohost.org/igunipodeb.vbs

J'ai bien un swapfile

**Comment by nemsia** [comment]
Zut je n'ai pas pris mon raspberry en vacances pour tester ça. ;)

Peut tu lancer les commandes suivantes, c'est la procédure d'installation, et voir si ça résout ton problème:
sudo su - mastodon
pushd ~/live
/opt/mastodon/.rbenv/versions/2.4.1/bin/gem install bundler
bin/bundle install --deployment --without development test
yarn install --production

**Comment by Rafi594** [comment]
ça ne fonctionne toujours pas le log
https://srvmaison.fr.nf/zerobin/?ca3bc21ad4cc39c9#4mfyMJCo56L04ps5jf5uRaVp+7rLnPivjaRLsAKC2Rc=

**Comment by nemsia** [comment]
Effectivement, il semble avoir besoin d'une dépendance supplémentaire sous arm, peut tu lancer la commande suivante:

apt-get install postgresql-server-dev-9.4

**Comment by nemsia** [comment]
Bonsoir,
Je vois que ton instance est de nouveau en ligne, peut tu m'indiquer si l'installation de postgresql-server-dev-9.4 suffit pour débloquer la mise à jour 1.5 sous arm ?

**Comment by Rafi594** [comment]
Oui l'installation de postgresql-server-dev-9.4 à réglé mon problème
