### ISSUE TITLE
401 Wrong token après m'être identifié en tant qu'utilisateur sur l'interface web de YunoHost

### ISSUE THREAD

**Issue by Kurokonomiyaki** [YunoHost-Apps/mastodon_ynh#51]
Bonjour,

Quand je me connecte en tant qu'utilisateur sur l'interface YunoHost (pas sur l'interface d'administration) alors que Mastodon tourne dans mon navigateur, le client web de Mastodon part en erreur (401 Le jeton d'accès n'est pas valide) au refresh et reste en erreur tant que je reste loggué sur l'interface YunoHost. Si je me déconnecte (ou que j'efface les cookies) de l'interface YunoHost, alors le client web se remet à fonctionner correctement après un refresh.

Merci beaucoup.

YunoHost 2.6.5
Mastodon 1.5

**Comment by nemsia** [comment]
Bonjour,
Ce problème est connu et une suppression des cookies ou une réinitialisation du profile du navigateur résout le problème.
Il n'arrive qu’après une installation fraiche ou une mise à jour de mastodon.

**Comment by Kurokonomiyaki** [comment]
Bonjour,
Je n'ai pas tenté une réinitialisation du profil, mais la suppression des cookies équivaut à une déconnexion. Si je me reconnecte en tant qu'utilisateur à l'interface YunoHost, l'erreur 401 revient côté Mastodon.

Est-ce qu'il existe des pistes de correction pour ce problème, autres qu'une action de l'utilisateur ? Est-ce lié à YunoHost directement ou au module mastodon_ynh ?

**Comment by nemsia** [comment]
tu peut essayer de commenter cette ligne dans le fichier nginx:
```
# Include SSOWAT user panel.
include conf.d/yunohost_panel.conf.inc;
```

**Comment by Silverscott** [comment]
Hello les gens !!

Suis également impacté par ce Bug d'erreur 401. Par contre je ne sais pas ou se trouve le le fichier nginx (d'ailleurs c'est lequel ?? J'imagine qu'il doit y'en avoir une pelletée..)

Amicalement

**Comment by yalh76** [comment]
Il n'est pas conseillé de modifier manuellement les fichiers nginx.

Pour le moment il existe un workaround: installer l'application en public et être déconnecté de la session Yunohost .

**Comment by yalh76** [comment]
Same as https://github.com/YunoHost-Apps/mastodon_ynh/issues/6

**Comment by yalh76** [comment]
issue continue in https://github.com/YunoHost-Apps/mastodon_ynh/issues/6
