### ISSUE TITLE
Failed to upgrade Raspberry Pi

### ISSUE THREAD

**Issue by Rafi594** [YunoHost-Apps/mastodon_ynh#59]
Hi

I have tried to upgrade Mastodon to 2.0 and I get this error

Warning: Installing ruby-2.4.2...
Warning: 
Warning: BUILD FAILED (Raspbian 8.0 using ruby-build 20170914-5-gf41e847)
Warning: 
Warning: Inspect or clean up the working tree at /tmp/ruby-build.20171027191210.13642
Warning: Results logged to /tmp/ruby-build.20171027191210.13642.log
Warning: 
Warning: Last 10 log lines:
Warning: Please submit a full bug report,
Warning: with preprocessed source if appropriate.
Warning: See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
Warning: The bug is not reproducible, so it is likely a hardware or OS problem.
Warning: Makefile:364: recipe for target 'array.o' failed
Warning: make: *** [array.o] Error 1
Warning: make: *** Waiting for unfinished jobs....
Warning: The bug is not reproducible, so it is likely a hardware or OS problem.
Warning: Makefile:364: recipe for target 'dir.o' failed
Warning: make: *** [dir.o] Error 1
Warning: -su: line 4: /opt/mastodon/.rbenv/versions/2.4.2/bin/ruby: No such file or directory

Thanks for you responses

**Comment by nemsia** [comment]
You are on raspberry pi ?

**Comment by Rafi594** [comment]
I use a Raspberry Pi 3

**Comment by nemsia** [comment]
After many try, i can't reproduce the problem on my raspberry 2. Install or upgrade work well.
How many swapfile size have you on your raspberry? Use "free" command to look.
You can test upgrade with ruby 2.4.1, with this command:
`yunohost app upgrade mastodon -u https://github.com/nemsia/mastodon_ynh/tree/v2-rb2.4.1 --verbose`

**Comment by Rafi594** [comment]
*** Error in `/usr/lib/gcc/arm-linux-gnueabihf/4.9/cc1': corrupted double-linked list: 0x022db1c0 ***
