### ISSUE TITLE
If rocket chat is installed the port 3000 coincide with Mastodon

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/mastodon_ynh#61]
Hi
I installed the Mastodon along side the RocketChat but I am redirected to the RocketChat as port 3000 is occupied by RocketChat. There should be option to change the port in manifest and check the port availability in the installation script.
See https://github.com/YunoHost-Apps/rocketchat_ynh/blob/master/scripts/install#L35
and https://github.com/YunoHost-Apps/mastodon_ynh/blob/master/conf/nginx.conf#L31

How should I change the port for mastodon now?

**Comment by anmol26s** [comment]
Can I use different port for Mastodon?

**Comment by nemsia** [comment]
I will add checking if the port 3000 is free, you can modify the port on mastodon-web and nginx.conf, ex. 3001 and restart mostodon-web and nginx.

**Comment by anmol26s** [comment]
I get 502 Bad Gateway error if I change the port 3001
Here is the log:
```
"GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "mast.domain.tld"
2017/11/17 21:46:08 [error] 28413#0: *22 connect() failed (111: Connection refused) while connecting to upstream, client: XXXXXXXXX, server: mast.domain.tld, request
: "GET / HTTP/1.1", upstream: "http://127.0.0.1:3001/", host: "mast.domain.tld"
```

**Comment by nemsia** [comment]
Modify port on /etc/systemd/system/mastodon-web.service and restart mastodon-web:
systemctl restart mastodon-web

**Comment by anmol26s** [comment]
Thanks! it worked

**Comment by nemsia** [comment]
Thanks you for your reports ;)
