### ISSUE TITLE
Is the instance open to Federation? 

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/mastodon_ynh#62]
I can not connect to other federation networks like Diaspora,Hubzilla and Friendica. Is the instance open for the these federated accounts?

**Comment by nemsia** [comment]
Hello,
I will try this with my test server, i didin't use Hubzilla or diaspora.
Good reason to try your yunohost apps ;)

28 novembre 2017 01:50 "anmol26s"  a écrit:
	I can not connect to other federation networks like Diaspora,Hubzilla and Friendica. Is the instance open for the these federated accounts?

**Comment by anmol26s** [comment]
It works with the federation. I have tested it with Hubzilla, so it should work with Frindica. Closing it for now. If there is a problem with other federated networks, please re-open the issue.
