### ISSUE TITLE
Erreur d'installation ruby 2.5.0

### ISSUE THREAD

**Issue by lesamarien** [YunoHost-Apps/mastodon_ynh#64]
Bonjour
Il est impossible de mettre à jour Mastodon vers la version 2.2.0. J'ai une erreur à cause de la version de Ruby. Il faut la 2.5.0 et l'install reste à la 2.4.2.
En faisant une réinstallation, le problème est le même.

Merci de votre aide.

**Comment by nemsia** [comment]
Fix on https://github.com/YunoHost-Apps/mastodon_ynh/pull/65

**Comment by nemsia** [comment]
Testé sur deux serveurs.
