### ISSUE TITLE
Mise à jour en 2.3.0

### ISSUE THREAD

**Issue by vincentux** [YunoHost-Apps/mastodon_ynh#66]
Est-ce possible de passer à la version 2.3.0 ou y a t il de modifs a apporter avant ?

**Comment by nemsia** [comment]
Pas encore fait les test, je regarde ça se soir.

**Comment by nemsia** [comment]
All work !!!!
Tu peut installer et avec une sauvegarde avant ça coute rien ;)

**Comment by vincentux** [comment]
Super merci ;)
