### ISSUE TITLE
[Feature] LDAP Integration

### ISSUE THREAD

**Issue by bgiesing** [YunoHost-Apps/mastodon_ynh#67]
Back in April 2017 when this package came out, somebody asked on the forums if integration with the SSO was coming. The response was "Yes, we will be able to do this, but Mastodon does not integrate LDAP at this time"

Well as of v2.3.0 (released 5 days ago as of this writing), LDAP is now supported so once the package is updated to v2.3.0, it should be integrated.

https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Enabling-LDAP-login.md

**Comment by nemsia** [comment]
This features is on my todo list, i will made with some tests to add this without breaking the actual installed mastodon instances.
ASAP ;)

**Comment by anmol26s** [comment]
I tried few Ldap yunohost settings for Mastodon without any success. This should be on priority and new branch should be created for testing it, so that everyone can know the progress from the branch and put in ideas to that branch.

**Comment by nemsia** [comment]
Same on my tests... I need to find ldap settings for mastodon before.

**Comment by anmol26s** [comment]
I have already tested various combinations you are trying. You should show these logs on mastodon page. I am sure they will show you the right solution as its an active community.

**Comment by gnouts** [comment]
I open up on issue on mastodon discourse here : https://discourse.joinmastodon.org/t/ldap-configuration-help-needed/1352

Also I just noticed this : https://github.com/tootsuite/mastodon/issues/6991
which indicate that mastodon doesn't support simple ldap auth. Could this be the main problem ?

What connection type are we suppose to use with Yunohost ?

**Comment by anmol26s** [comment]
Yunohost don't use start_tls. LDAP_METHOD should have **plain** .

**Comment by Thatoo** [comment]
Waiting for LDAP to install Mastodon (and peerube) on my familly yunohost [CHATONS](http://chatons.org/) server.

**Comment by Thatoo** [comment]
@gnouts : did you get any progress on that subject?
I see someone asked you a question recently on discourse. Have you noticed it?

**Comment by gnouts** [comment]
@Thatoo :  Thanks for the ping, I just answered on discourse. But no, no progress...

**Comment by Thatoo** [comment]
It seems that pleroma manage to implement LDAP, https://git.pleroma.social/pleroma/pleroma/issues/203, and yalh76, the maintainer of the yunohost pleroma package is working on it, https://github.com/YunoHost-Apps/pleroma_ynh/issues/28 .
Maybe their work could help to make LDAP coming on more fediverse package [on Yunohost].
