### ISSUE TITLE
Hard-coded references to postgresql-9.4 might break compatibility with Stretch

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/mastodon_ynh#75]
Hellow,

I see that there are some hard-coded reference to postgresql 9.4 in the code of this package : 

e.g. : 
https://github.com/YunoHost-Apps/mastodon_ynh/blob/master/scripts/upgrade#L68

Since Stretch now has postgresql 9.6, this might break the installation or other functionalities of this app on Stretch / Yunohost 3.x

**Comment by nemsia** [comment]
I with try to use postgresql-server-dev-all, this package is only need on raspberry pi.
This app use backport repo, that with be problem, right ?

**Comment by alexAubin** [comment]
>This app use backport repo, that with be problem, right ?

Hmmm idk... Surely adding jessie-backports in stretch is really weird so that needs to be adapted somehow :P But maybe it's just a matter of having a `if jessie; ... else ...` like in https://github.com/YunoHost-Apps/nextcloud_ynh/blob/master/scripts/_common.sh#L8

(I think ffmpeg should be available directly in stretch, without the need of backports)
