### ISSUE TITLE
Password should not be saved in yunohost settings

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/mastodon_ynh#83]
Hi
I am wondering what is required for saving the password in the yunohost settings? I have already changed my password and setting has old saved password. Little weird :confused:  
https://github.com/YunoHost-Apps/mastodon_ynh/blob/master/scripts/install#L34

**Comment by nemsia** [comment]
This password is only used on install to create the admin account, no relation to yunohost password.
The LDAP integration will be the good solution to remove it soon.

**Comment by nemsia** [comment]
Fixed by https://github.com/YunoHost-Apps/mastodon_ynh/pull/100

**Comment by anmol26s** [comment]
Of course this should be closed now.
